version: "3.8"
services:
  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379
  thales-api:
    restart: always
    image: thalesmarket/api
    depends_on:
      - redis
    environment:
      - "REDIS_URL=redis://redis:6379"
      - "INFURA_URL=https://mainnet.infura.io/v3/bca778c2b71d491cb704394855f80e9a"
    ports:
      - 3002:3002
  overtime-api:
    restart: always
    image: thalesmarket/overtime-api
    depends_on:
      - redis
    environment:
      - "REDIS_URL=redis://redis:6379"
      - "CHAINNODES_ID=a8fd9538-2338-4e68-88d2-0922d02866e6"
volumes:
  redis-data:
