version: "3.8"
services:
  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379
  thales-api:
    restart: always
    image: thalesmarket/api
    depends_on:
      - redis
    environment:
      - "REDIS_URL=redis://redis:6379"
      - "INFURA_URL="
      - "CHAINNODES_ID="
    ports:
      - 3002:3002
  overtime-api:
    restart: always
    image: thalesmarket/overtime-api
    depends_on:
      - redis
    environment:
      - "REDIS_URL=redis://redis:6379"
      - "CHAINNODES_ID="
  thales-io:
    restart: always
    image: thalesmarket/thales-io
    depends_on:
      - redis
    environment:
      - "REDIS_URL=redis://redis:6379"
      - "DUNE_API_KEY="
volumes:
  redis-data:
