const { NETWORK } = require("./networks");

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

const SUPPORTED_NETWORKS = [
  NETWORK.Optimism,
  NETWORK.Arbitrum,
  NETWORK.Base,
  NETWORK.Polygon,
  NETWORK.ZkSync,
  NETWORK.BlastSepolia,
  NETWORK.ZkSyncSepolia,
  NETWORK.OptimismGoerli,
];
const SUPPORTED_ASSETS = ["BTC", "ETH"];

const MAX_BUYIN_COLLATERAL_CONVERSION_BUFFER = 10;

module.exports = { ZERO_ADDRESS, SUPPORTED_NETWORKS, SUPPORTED_ASSETS, MAX_BUYIN_COLLATERAL_CONVERSION_BUFFER };
