const { NETWORK } = require("./networks");
const { CRYPTO_CURRENCY_MAP } = require("./currency");

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

const SUPPORTED_NETWORKS = [
  NETWORK.Optimism,
  NETWORK.Arbitrum,
  NETWORK.Base,
  NETWORK.Polygon,
  NETWORK.ZkSync,
  NETWORK.BlastSepolia,
  NETWORK.ZkSyncSepolia,
  NETWORK.OptimismGoerli,
];
const SUPPORTED_ASSETS = [CRYPTO_CURRENCY_MAP.BTC, CRYPTO_CURRENCY_MAP.ETH];

const SUPPORTED_COLLATERALS = {
  [NETWORK.Optimism]: [
    CRYPTO_CURRENCY_MAP.sUSD,
    CRYPTO_CURRENCY_MAP.DAI,
    CRYPTO_CURRENCY_MAP.USDC,
    CRYPTO_CURRENCY_MAP.USDT,
    CRYPTO_CURRENCY_MAP.OP,
    CRYPTO_CURRENCY_MAP.WETH,
    CRYPTO_CURRENCY_MAP.ETH,
  ],
  [NETWORK.OptimismGoerli]: [CRYPTO_CURRENCY_MAP.sUSD],
  [NETWORK.PolygonMainnet]: [CRYPTO_CURRENCY_MAP.USDCe],
  [NETWORK.Base]: [
    CRYPTO_CURRENCY_MAP.USDbC,
    CRYPTO_CURRENCY_MAP.USDC,
    CRYPTO_CURRENCY_MAP.WETH,
    CRYPTO_CURRENCY_MAP.ETH,
  ],
  [NETWORK.Arbitrum]: [
    CRYPTO_CURRENCY_MAP.USDCe,
    CRYPTO_CURRENCY_MAP.USDC,
    CRYPTO_CURRENCY_MAP.DAI,
    CRYPTO_CURRENCY_MAP.USDT,
    CRYPTO_CURRENCY_MAP.ARB,
    CRYPTO_CURRENCY_MAP.WETH,
    CRYPTO_CURRENCY_MAP.ETH,
  ],
  [NETWORK.ZkSync]: [CRYPTO_CURRENCY_MAP.USDC],
  [NETWORK.ZkSyncSepolia]: [CRYPTO_CURRENCY_MAP.sUSD],
  [NETWORK.BlastSepolia]: [CRYPTO_CURRENCY_MAP.sUSD],
};

const MAX_BUYIN_COLLATERAL_CONVERSION_BUFFER = 10;
const STABLECOIN_CONVERSION_BUFFER_PERCENTAGE = 0.005; // 0.5%
const ALTCOIN_CONVERSION_BUFFER_PERCENTAGE = 0.01; // 1%

module.exports = {
  ZERO_ADDRESS,
  SUPPORTED_NETWORKS,
  SUPPORTED_ASSETS,
  SUPPORTED_COLLATERALS,
  MAX_BUYIN_COLLATERAL_CONVERSION_BUFFER,
  STABLECOIN_CONVERSION_BUFFER_PERCENTAGE,
  ALTCOIN_CONVERSION_BUFFER_PERCENTAGE,
};
