const BET_TYPE = {
  Winner: 0,
  Spread: 10001,
  Total: 10002,
  DoubleChance: 10003,
  WinnerTotal: 10004,
  TotalOddEven: 10005,
  HalftimeFulltime: 10006,
  Goals: 10007,
  HalftimeFulltimeGoals: 10008,
  Spread2: 10013,
  Total2: 10014,
  Homeruns: 11010,
  Strikeouts: 11019,
  PassingYards: 11051,
  PassingTouchdowns: 11052,
  RushingYards: 11053,
  ReceivingYards: 11057,
  Touchdowns: 11055,
  FieldGoalsMade: 11060,
  PitcherHitsAllowed: 11047,
  Points: 11029,
  Shots: 11097,
  Goals: 11086,
  HitsRecorded: 11012,
  Rebounds: 11035,
  Assists: 11039,
  DoubleDouble: 11087,
  TripleDouble: 11088,
  Receptions: 11058,
  FirstTouchdown: 11049,
  LastTouchdown: 11056,
  ThreePointsMade: 11038,

  FirstPeriodWinner: 10021,
  SecondPeriodWinner: 10022,
  ThirdPeriodWinner: 10023,
  FourthPeriodWinner: 10024,
  FifthPeriodWinner: 10025,
  SixthPeriodWinner: 10026,
  SeventhPeriodWinner: 10027,
  EightPeriodWinner: 10028,
  NinthPeriodWinner: 10029,
  FirstPeriodTotal: 10031,
  SecondPeriodTotal: 10032,
  ThirdPeriodTotal: 10033,
  FourthPeriodTotal: 10034,
  FifthPeriodTotal: 10035,
  SixthPeriodTotal: 10036,
  SeventhPeriodTotal: 10037,
  EightPeriodTotal: 10038,
  NinthPeriodTotal: 10039,
  FirstPeriodSpread: 10041,
  SecondPeriodSpread: 10042,
  ThirdPeriodSpread: 10043,
  FourthPeriodSpread: 10044,
  FifthPeriodSpread: 10045,
  SixthPeriodSpread: 10046,
  SeventhPeriodSpread: 10047,
  EightPeriodSpread: 10048,
  NinthPeriodSpread: 10049,

  FirstPeriodWinner2: 10051,
  SecondPeriodWinner2: 10052,
  ThirdPeriodWinner2: 10053,
  FourthPeriodWinner2: 10054,
  FifthPeriodWinner2: 10055,
  SixthPeriodWinner2: 10056,
  SeventhPeriodWinner2: 10057,
  EightPeriodWinner2: 10058,
  NinthPeriodWinner2: 10059,
  FirstPeriodTotal2: 10061,
  SecondPeriodTotal2: 10062,
  ThirdPeriodTotal2: 10063,
  FourthPeriodTotal2: 10064,
  FifthPeriodTotal2: 10065,
  SixthPeriodTotal2: 10066,
  SeventhPeriodTotal2: 10067,
  EightPeriodTotal2: 10068,
  NinthPeriodTotal2: 10069,
  FirstPeriodSpread2: 10071,
  SecondPeriodSpread2: 10072,
  ThirdPeriodSpread2: 10073,
  FourthPeriodSpread2: 10074,
  FifthPeriodSpread2: 10075,
  SixthPeriodSpread2: 10076,
  SeventhPeriodSpread2: 10077,
  EightPeriodSpread2: 10078,
  NinthPeriodSpread2: 10079,

  FirstPeriodTotalOddEven: 10081,
  SecondPeriodTotalOddEven: 10082,
  ThirdPeriodTotalOddEven: 10083,
  FourthPeriodTotalOddEven: 10084,
  FifthPeriodTotalOddEven: 10085,
  SixthPeriodTotalOddEven: 10086,
  SeventhPeriodTotalOddEven: 10087,
  EightPeriodTotalOddEven: 10088,
  NinthPeriodTotalOddEven: 10089,
  FirstPeriodTotal2OddEven: 10091,
  SecondPeriodTotal2OddEven: 10092,
  ThirdPeriodTotal2OddEven: 10093,
  FourthPeriodTotal2OddEven: 10094,
  FifthPeriodTotal2OddEven: 10095,
  SixthPeriodTotal2OddEven: 10096,
  SeventhPeriodTotal2OddEven: 10097,
  EightPeriodTotal2OddEven: 10098,
  NinthPeriodTotal2OddEven: 10099,
};

const MARKET_TYPE = {
  [BET_TYPE.Winner]: "winner",
  [BET_TYPE.Spread]: "spread",
  [BET_TYPE.Total]: "total",
  [BET_TYPE.DoubleChance]: "doubleChance",
  [BET_TYPE.WinnerTotal]: "winnerTotal",
  [BET_TYPE.TotalOddEven]: "totalOddEven",
  [BET_TYPE.HalftimeFulltime]: "halftimeFulltime",
  [BET_TYPE.Goals]: "goals",
  [BET_TYPE.HalftimeFulltimeGoals]: "halftimeFulltimeGoals",
  [BET_TYPE.Spread2]: "halftimeSpread",
  [BET_TYPE.Total2]: "halftimeTotal",
  [BET_TYPE.Homeruns]: "homeruns",
  [BET_TYPE.Strikeouts]: "strikeouts",
  [BET_TYPE.PassingYards]: "passingYards",
  [BET_TYPE.PassingTouchdowns]: "passingTouchdowns",
  [BET_TYPE.RushingYards]: "rushingYards",
  [BET_TYPE.ReceivingYards]: "receivingYards",
  [BET_TYPE.Touchdowns]: "touchdowns",
  [BET_TYPE.FieldGoalsMade]: "fieldGoalsMade",
  [BET_TYPE.PitcherHitsAllowed]: "pitcherHitsAllowed",
  [BET_TYPE.Points]: "points",
  [BET_TYPE.Shots]: "shots",
  [BET_TYPE.Goals]: "goals",
  [BET_TYPE.HitsRecorded]: "hitsRecorded",
  [BET_TYPE.Rebounds]: "rebounds",
  [BET_TYPE.Assists]: "assists",
  [BET_TYPE.DoubleDouble]: "doubleDouble",
  [BET_TYPE.TripleDouble]: "tripleDouble",
  [BET_TYPE.Receptions]: "receptions",
  [BET_TYPE.FirstTouchdown]: "firstTouchdown",
  [BET_TYPE.LastTouchdown]: "lastTouchdown",
  [BET_TYPE.ThreePointsMade]: "threePointsMade",

  [BET_TYPE.FirstPeriodWinner]: "firstPeriodWinner",
  [BET_TYPE.SecondPeriodWinner]: "secondPeriodWinner",
  [BET_TYPE.ThirdPeriodWinner]: "thirdPeriodWinner",
  [BET_TYPE.FourthPeriodWinner]: "fourthPeriodWinner",
  [BET_TYPE.FifthPeriodWinner]: "fifthPeriodWinner",
  [BET_TYPE.SixthPeriodWinner]: "sixthPeriodWinner",
  [BET_TYPE.SeventhPeriodWinner]: "seventhPeriodWinner",
  [BET_TYPE.EightPeriodWinner]: "eightPeriodWinner",
  [BET_TYPE.NinthPeriodWinner]: "ninthPeriodWinner",
  [BET_TYPE.FirstPeriodTotal]: "firstPeriodTotal",
  [BET_TYPE.SecondPeriodTotal]: "secondPeriodTotal",
  [BET_TYPE.ThirdPeriodTotal]: "thirdPeriodTotal",
  [BET_TYPE.FourthPeriodTotal]: "fourthPeriodTotal",
  [BET_TYPE.FifthPeriodTotal]: "fifthPeriodTotal",
  [BET_TYPE.SixthPeriodTotal]: "sixthPeriodTotal",
  [BET_TYPE.SeventhPeriodTotal]: "seventhPeriodTotal",
  [BET_TYPE.EightPeriodTotal]: "eightPeriodTotal",
  [BET_TYPE.NinthPeriodTotal]: "ninthPeriodTotal",
  [BET_TYPE.FirstPeriodSpread]: "firstPeriodSpread",
  [BET_TYPE.SecondPeriodSpread]: "secondPeriodSpread",
  [BET_TYPE.ThirdPeriodSpread]: "thirdPeriodSpread",
  [BET_TYPE.FourthPeriodSpread]: "fourthPeriodSpread",
  [BET_TYPE.FifthPeriodSpread]: "fifthPeriodSpread",
  [BET_TYPE.SixthPeriodSpread]: "sixthPeriodSpread",
  [BET_TYPE.SeventhPeriodSpread]: "seventhPeriodSpread",
  [BET_TYPE.EightPeriodSpread]: "eightPeriodSpread",
  [BET_TYPE.NinthPeriodSpread]: "ninthPeriodSpread",

  [BET_TYPE.FirstPeriodWinner2]: "firstPeriodWinner2",
  [BET_TYPE.SecondPeriodWinner2]: "secondPeriodWinner2",
  [BET_TYPE.ThirdPeriodWinner2]: "thirdPeriodWinner2",
  [BET_TYPE.FourthPeriodWinner2]: "fourthPeriodWinner2",
  [BET_TYPE.FifthPeriodWinner2]: "fifthPeriodWinner2",
  [BET_TYPE.SixthPeriodWinner2]: "sixthPeriodWinner2",
  [BET_TYPE.SeventhPeriodWinner2]: "seventhPeriodWinner2",
  [BET_TYPE.EightPeriodWinner2]: "eightPeriodWinner2",
  [BET_TYPE.NinthPeriodWinner2]: "ninthPeriodWinner2",
  [BET_TYPE.FirstPeriodTotal2]: "firstPeriodTotal2",
  [BET_TYPE.SecondPeriodTotal2]: "secondPeriodTotal2",
  [BET_TYPE.ThirdPeriodTotal2]: "thirdPeriodTotal2",
  [BET_TYPE.FourthPeriodTotal2]: "fourthPeriodTotal2",
  [BET_TYPE.FifthPeriodTotal2]: "fifthPeriodTotal2",
  [BET_TYPE.SixthPeriodTotal2]: "sixthPeriodTotal2",
  [BET_TYPE.SeventhPeriodTotal2]: "seventhPeriodTotal2",
  [BET_TYPE.EightPeriodTotal2]: "eightPeriodTotal2",
  [BET_TYPE.NinthPeriodTotal2]: "ninthPeriodTotal2",
  [BET_TYPE.FirstPeriodSpread2]: "firstPeriodSpread2",
  [BET_TYPE.SecondPeriodSpread2]: "secondPeriodSpread2",
  [BET_TYPE.ThirdPeriodSpread2]: "thirdPeriodSpread2",
  [BET_TYPE.FourthPeriodSpread2]: "fourthPeriodSpread2",
  [BET_TYPE.FifthPeriodSpread2]: "fifthPeriodSpread2",
  [BET_TYPE.SixthPeriodSpread2]: "sixthPeriodSpread2",
  [BET_TYPE.SeventhPeriodSpread2]: "seventhPeriodSpread2",
  [BET_TYPE.EightPeriodSpread2]: "eightPeriodSpread2",
  [BET_TYPE.NinthPeriodSpread2]: "ninthPeriodSpread2",

  [BET_TYPE.FirstPeriodTotalOddEven]: "firstPeriodTotalOddEven",
  [BET_TYPE.SecondPeriodTotalOddEven]: "secondPeriodTotalOddEven",
  [BET_TYPE.ThirdPeriodTotalOddEven]: "thirdPeriodTotalOddEven",
  [BET_TYPE.FourthPeriodTotalOddEven]: "fourthPeriodTotalOddEven",
  [BET_TYPE.FifthPeriodTotalOddEven]: "fifthPeriodTotalOddEven",
  [BET_TYPE.SixthPeriodTotalOddEven]: "sixthPeriodTotalOddEven",
  [BET_TYPE.SeventhPeriodTotalOddEven]: "seventhPeriodTotalOddEven",
  [BET_TYPE.EightPeriodTotalOddEven]: "eightPeriodTotalOddEven",
  [BET_TYPE.NinthPeriodTotalOddEven]: "ninthPeriodTotalOddEven",
  [BET_TYPE.FirstPeriodTotal2OddEven]: "firstPeriodTotal2OddEven",
  [BET_TYPE.SecondPeriodTotal2OddEven]: "secondPeriodTotal2OddEven",
  [BET_TYPE.ThirdPeriodTotal2OddEven]: "thirdPeriodTotal2OddEven",
  [BET_TYPE.FourthPeriodTotal2OddEven]: "fourthPeriodTotal2OddEven",
  [BET_TYPE.FifthPeriodTotal2OddEven]: "fifthPeriodTotal2OddEven",
  [BET_TYPE.SixthPeriodTotal2OddEven]: "sixthPeriodTotal2OddEven",
  [BET_TYPE.SeventhPeriodTotal2OddEven]: "seventhPeriodTotal2OddEven",
  [BET_TYPE.EightPeriodTotal2OddEven]: "eightPeriodTotal2OddEven",
  [BET_TYPE.NinthPeriodTotal2OddEven]: "ninthPeriodTotal2OddEven",
};

const PLAYER_PROPS_BET_TYPES = [
  BET_TYPE.Homeruns,
  BET_TYPE.Strikeouts,
  BET_TYPE.PassingYards,
  BET_TYPE.PassingTouchdowns,
  BET_TYPE.RushingYards,
  BET_TYPE.ReceivingYards,
  BET_TYPE.Touchdowns,
  BET_TYPE.FieldGoalsMade,
  BET_TYPE.PitcherHitsAllowed,
  BET_TYPE.Points,
  BET_TYPE.Shots,
  BET_TYPE.Goals,
  BET_TYPE.HitsRecorded,
  BET_TYPE.Rebounds,
  BET_TYPE.Assists,
  BET_TYPE.DoubleDouble,
  BET_TYPE.TripleDouble,
  BET_TYPE.Receptions,
  BET_TYPE.FirstTouchdown,
  BET_TYPE.LastTouchdown,
  BET_TYPE.ThreePointsMade,
];

const ONE_SIDER_PLAYER_PROPS_BET_TYPES = [
  BET_TYPE.Touchdowns,
  BET_TYPE.Goals,
  BET_TYPE.FirstTouchdown,
  BET_TYPE.LastTouchdown,
];
const SPECIAL_YES_NO_BET_TYPES = [BET_TYPE.DoubleDouble, BET_TYPE.TripleDouble];

const ODDS_TYPE = {
  American: "american-odds",
  Decimal: "decimal-odds",
  AMM: "normalized-implied-odds",
};

const POSITION_NAME = {
  Home: "home",
  Away: "away",
  Draw: "draw",
};

const POSITION_TYPE = {
  Home: 0,
  Away: 1,
  Draw: 2,
};

const FINAL_RESULT_TYPE = {
  Canceled: 0,
  Home: 1,
  Away: 2,
  Draw: 3,
};

const POSITION_NAME_TYPE_MAP = {
  [POSITION_NAME.Home]: POSITION_TYPE.Home,
  [POSITION_NAME.Away]: POSITION_TYPE.Away,
  [POSITION_NAME.Draw]: POSITION_TYPE.Draw,
};

const FINAL_RESULT_TYPE_POSITION_TYPE_MAP = {
  [FINAL_RESULT_TYPE.Home]: POSITION_TYPE.Home,
  [FINAL_RESULT_TYPE.Away]: POSITION_TYPE.Away,
  [FINAL_RESULT_TYPE.Draw]: POSITION_TYPE.Draw,
};

const MARKET_DURATION_IN_DAYS = 90;
const PARLAY_MAXIMUM_QUOTE = 0.01449275;

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

const PARLAY_CONTRACT_ERROR_MESSAGE = {
  RiskPerCombExceeded: "RiskPerComb exceeded",
  SameTeamOnParlay: "SameTeamOnParlay",
};

const STATUS = {
  Open: 0,
  Paused: 1,
  Resolved: 10,
  Canceled: 255,
};

const MAX_PERCENTAGE_DIFF_BETWEEN_ODDS = 10;
const MIN_ODDS_FOR_DIFF_CHECKING = 0.2;

module.exports = {
  BET_TYPE,
  MARKET_TYPE,
  PLAYER_PROPS_BET_TYPES,
  ONE_SIDER_PLAYER_PROPS_BET_TYPES,
  ODDS_TYPE,
  MARKET_DURATION_IN_DAYS,
  POSITION_NAME,
  POSITION_TYPE,
  POSITION_NAME_TYPE_MAP,
  PARLAY_MAXIMUM_QUOTE,
  FINAL_RESULT_TYPE_POSITION_TYPE_MAP,
  ZERO_ADDRESS,
  PARLAY_CONTRACT_ERROR_MESSAGE,
  SPECIAL_YES_NO_BET_TYPES,
  STATUS,
  MAX_PERCENTAGE_DIFF_BETWEEN_ODDS,
  MIN_ODDS_FOR_DIFF_CHECKING,
};
