const MarketType = {
  Winner: 0,

  Spread: 10001,
  Total: 10002,
  DoubleChance: 10003,
  WinnerTotal: 10004,
  TotalOddEven: 10005,
  HalftimeFulltime: 10006,
  Goals: 10007,
  HalftimeFulltimeGoals: 10008,
  BothTeamsToScore: 10009,
  Winner2: 10011,
  Winner3: 10012,
  Spread2: 10013,
  Total2: 10014,
  Homeruns: 11010,
  Strikeouts: 11019,
  PassingYards: 11051,
  PassingTouchdowns: 11052,
  RushingYards: 11053,
  ReceivingYards: 11057,
  Touchdowns: 11055,
  FieldGoalsMade: 11060,
  PitcherHitsAllowed: 11047,
  Points: 11029,
  Shots: 11097,
  Goals: 11086,
  HitsRecorded: 11012,
  Rebounds: 11035,
  Assists: 11039,
  DoubleDouble: 11087,
  TripleDouble: 11088,
  Receptions: 11058,
  FirstTouchdown: 11049,
  LastTouchdown: 11056,
  ThreePointsMade: 11038,

  FirstPeriodWinner: 10021,
  SecondPeriodWinner: 10022,
  ThirdPeriodWinner: 10023,
  FourthPeriodWinner: 10024,
  FifthPeriodWinner: 10025,
  SixthPeriodWinner: 10026,
  SeventhPeriodWinner: 10027,
  EightPeriodWinner: 10028,
  NinthPeriodWinner: 10029,
  FirstPeriodTotal: 10031,
  SecondPeriodTotal: 10032,
  ThirdPeriodTotal: 10033,
  FourthPeriodTotal: 10034,
  FifthPeriodTotal: 10035,
  SixthPeriodTotal: 10036,
  SeventhPeriodTotal: 10037,
  EightPeriodTotal: 10038,
  NinthPeriodTotal: 10039,
  FirstPeriodSpread: 10041,
  SecondPeriodSpread: 10042,
  ThirdPeriodSpread: 10043,
  FourthPeriodSpread: 10044,
  FifthPeriodSpread: 10045,
  SixthPeriodSpread: 10046,
  SeventhPeriodSpread: 10047,
  EightPeriodSpread: 10048,
  NinthPeriodSpread: 10049,

  FirstPeriodWinner2: 10051,
  SecondPeriodWinner2: 10052,
  ThirdPeriodWinner2: 10053,
  FourthPeriodWinner2: 10054,
  FifthPeriodWinner2: 10055,
  SixthPeriodWinner2: 10056,
  SeventhPeriodWinner2: 10057,
  EightPeriodWinner2: 10058,
  NinthPeriodWinner2: 10059,
  FirstPeriodTotal2: 10061,
  SecondPeriodTotal2: 10062,
  ThirdPeriodTotal2: 10063,
  FourthPeriodTotal2: 10064,
  FifthPeriodTotal2: 10065,
  SixthPeriodTotal2: 10066,
  SeventhPeriodTotal2: 10067,
  EightPeriodTotal2: 10068,
  NinthPeriodTotal2: 10069,
  FirstPeriodSpread2: 10071,
  SecondPeriodSpread2: 10072,
  ThirdPeriodSpread2: 10073,
  FourthPeriodSpread2: 10074,
  FifthPeriodSpread2: 10075,
  SixthPeriodSpread2: 10076,
  SeventhPeriodSpread2: 10077,
  EightPeriodSpread2: 10078,
  NinthPeriodSpread2: 10079,

  FirstPeriodTotalOddEven: 10081,
  SecondPeriodTotalOddEven: 10082,
  ThirdPeriodTotalOddEven: 10083,
  FourthPeriodTotalOddEven: 10084,
  FifthPeriodTotalOddEven: 10085,
  SixthPeriodTotalOddEven: 10086,
  SeventhPeriodTotalOddEven: 10087,
  EightPeriodTotalOddEven: 10088,
  NinthPeriodTotalOddEven: 10089,
  FirstPeriodTotal2OddEven: 10091,
  SecondPeriodTotal2OddEven: 10092,
  ThirdPeriodTotal2OddEven: 10093,
  FourthPeriodTotal2OddEven: 10094,
  FifthPeriodTotal2OddEven: 10095,
  SixthPeriodTotal2OddEven: 10096,
  SeventhPeriodTotal2OddEven: 10097,
  EightPeriodTotal2OddEven: 10098,
  NinthPeriodTotal2OddEven: 10099,

  FirstPeriodBothTeamsToScore: 10101,
  SecondPeriodBothTeamsToScore: 10102,
  ThirdPeriodBothTeamsToScore: 10103,
  FourthPeriodBothTeamsToScore: 10104,
  FifthPeriodBothTeamsToScore: 10105,
  SixthPeriodBothTeamsToScore: 10106,
  SeventhPeriodBothTeamsToScore: 10107,
  EightPeriodBothTeamsToScore: 10108,
  NinthPeriodBothTeamsToScore: 10109,
};

const MARKET_TYPE = {
  [MarketType.Winner]: "winner",
  [MarketType.Spread]: "spread",
  [MarketType.Total]: "total",
  [MarketType.DoubleChance]: "doubleChance",
  [MarketType.WinnerTotal]: "winnerTotal",
  [MarketType.TotalOddEven]: "totalOddEven",
  [MarketType.HalftimeFulltime]: "halftimeFulltime",
  [MarketType.Goals]: "goals",
  [MarketType.HalftimeFulltimeGoals]: "halftimeFulltimeGoals",
  [MarketType.BothTeamsToScore]: "bothTeamsToScore",
  [MarketType.Winner2]: "winner2",
  [MarketType.Winner3]: "winner3",
  [MarketType.Spread2]: "halftimeSpread",
  [MarketType.Total2]: "halftimeTotal",
  [MarketType.Homeruns]: "homeruns",
  [MarketType.Strikeouts]: "strikeouts",
  [MarketType.PassingYards]: "passingYards",
  [MarketType.PassingTouchdowns]: "passingTouchdowns",
  [MarketType.RushingYards]: "rushingYards",
  [MarketType.ReceivingYards]: "receivingYards",
  [MarketType.Touchdowns]: "touchdowns",
  [MarketType.FieldGoalsMade]: "fieldGoalsMade",
  [MarketType.PitcherHitsAllowed]: "pitcherHitsAllowed",
  [MarketType.Points]: "points",
  [MarketType.Shots]: "shots",
  [MarketType.Goals]: "goals",
  [MarketType.HitsRecorded]: "hitsRecorded",
  [MarketType.Rebounds]: "rebounds",
  [MarketType.Assists]: "assists",
  [MarketType.DoubleDouble]: "doubleDouble",
  [MarketType.TripleDouble]: "tripleDouble",
  [MarketType.Receptions]: "receptions",
  [MarketType.FirstTouchdown]: "firstTouchdown",
  [MarketType.LastTouchdown]: "lastTouchdown",
  [MarketType.ThreePointsMade]: "threePointsMade",

  [MarketType.FirstPeriodWinner]: "firstPeriodWinner",
  [MarketType.SecondPeriodWinner]: "secondPeriodWinner",
  [MarketType.ThirdPeriodWinner]: "thirdPeriodWinner",
  [MarketType.FourthPeriodWinner]: "fourthPeriodWinner",
  [MarketType.FifthPeriodWinner]: "fifthPeriodWinner",
  [MarketType.SixthPeriodWinner]: "sixthPeriodWinner",
  [MarketType.SeventhPeriodWinner]: "seventhPeriodWinner",
  [MarketType.EightPeriodWinner]: "eightPeriodWinner",
  [MarketType.NinthPeriodWinner]: "ninthPeriodWinner",
  [MarketType.FirstPeriodTotal]: "firstPeriodTotal",
  [MarketType.SecondPeriodTotal]: "secondPeriodTotal",
  [MarketType.ThirdPeriodTotal]: "thirdPeriodTotal",
  [MarketType.FourthPeriodTotal]: "fourthPeriodTotal",
  [MarketType.FifthPeriodTotal]: "fifthPeriodTotal",
  [MarketType.SixthPeriodTotal]: "sixthPeriodTotal",
  [MarketType.SeventhPeriodTotal]: "seventhPeriodTotal",
  [MarketType.EightPeriodTotal]: "eightPeriodTotal",
  [MarketType.NinthPeriodTotal]: "ninthPeriodTotal",
  [MarketType.FirstPeriodSpread]: "firstPeriodSpread",
  [MarketType.SecondPeriodSpread]: "secondPeriodSpread",
  [MarketType.ThirdPeriodSpread]: "thirdPeriodSpread",
  [MarketType.FourthPeriodSpread]: "fourthPeriodSpread",
  [MarketType.FifthPeriodSpread]: "fifthPeriodSpread",
  [MarketType.SixthPeriodSpread]: "sixthPeriodSpread",
  [MarketType.SeventhPeriodSpread]: "seventhPeriodSpread",
  [MarketType.EightPeriodSpread]: "eightPeriodSpread",
  [MarketType.NinthPeriodSpread]: "ninthPeriodSpread",

  [MarketType.FirstPeriodWinner2]: "firstPeriodWinner2",
  [MarketType.SecondPeriodWinner2]: "secondPeriodWinner2",
  [MarketType.ThirdPeriodWinner2]: "thirdPeriodWinner2",
  [MarketType.FourthPeriodWinner2]: "fourthPeriodWinner2",
  [MarketType.FifthPeriodWinner2]: "fifthPeriodWinner2",
  [MarketType.SixthPeriodWinner2]: "sixthPeriodWinner2",
  [MarketType.SeventhPeriodWinner2]: "seventhPeriodWinner2",
  [MarketType.EightPeriodWinner2]: "eightPeriodWinner2",
  [MarketType.NinthPeriodWinner2]: "ninthPeriodWinner2",
  [MarketType.FirstPeriodTotal2]: "firstPeriodTotal2",
  [MarketType.SecondPeriodTotal2]: "secondPeriodTotal2",
  [MarketType.ThirdPeriodTotal2]: "thirdPeriodTotal2",
  [MarketType.FourthPeriodTotal2]: "fourthPeriodTotal2",
  [MarketType.FifthPeriodTotal2]: "fifthPeriodTotal2",
  [MarketType.SixthPeriodTotal2]: "sixthPeriodTotal2",
  [MarketType.SeventhPeriodTotal2]: "seventhPeriodTotal2",
  [MarketType.EightPeriodTotal2]: "eightPeriodTotal2",
  [MarketType.NinthPeriodTotal2]: "ninthPeriodTotal2",
  [MarketType.FirstPeriodSpread2]: "firstPeriodSpread2",
  [MarketType.SecondPeriodSpread2]: "secondPeriodSpread2",
  [MarketType.ThirdPeriodSpread2]: "thirdPeriodSpread2",
  [MarketType.FourthPeriodSpread2]: "fourthPeriodSpread2",
  [MarketType.FifthPeriodSpread2]: "fifthPeriodSpread2",
  [MarketType.SixthPeriodSpread2]: "sixthPeriodSpread2",
  [MarketType.SeventhPeriodSpread2]: "seventhPeriodSpread2",
  [MarketType.EightPeriodSpread2]: "eightPeriodSpread2",
  [MarketType.NinthPeriodSpread2]: "ninthPeriodSpread2",

  [MarketType.FirstPeriodTotalOddEven]: "firstPeriodTotalOddEven",
  [MarketType.SecondPeriodTotalOddEven]: "secondPeriodTotalOddEven",
  [MarketType.ThirdPeriodTotalOddEven]: "thirdPeriodTotalOddEven",
  [MarketType.FourthPeriodTotalOddEven]: "fourthPeriodTotalOddEven",
  [MarketType.FifthPeriodTotalOddEven]: "fifthPeriodTotalOddEven",
  [MarketType.SixthPeriodTotalOddEven]: "sixthPeriodTotalOddEven",
  [MarketType.SeventhPeriodTotalOddEven]: "seventhPeriodTotalOddEven",
  [MarketType.EightPeriodTotalOddEven]: "eightPeriodTotalOddEven",
  [MarketType.NinthPeriodTotalOddEven]: "ninthPeriodTotalOddEven",
  [MarketType.FirstPeriodTotal2OddEven]: "firstPeriodTotal2OddEven",
  [MarketType.SecondPeriodTotal2OddEven]: "secondPeriodTotal2OddEven",
  [MarketType.ThirdPeriodTotal2OddEven]: "thirdPeriodTotal2OddEven",
  [MarketType.FourthPeriodTotal2OddEven]: "fourthPeriodTotal2OddEven",
  [MarketType.FifthPeriodTotal2OddEven]: "fifthPeriodTotal2OddEven",
  [MarketType.SixthPeriodTotal2OddEven]: "sixthPeriodTotal2OddEven",
  [MarketType.SeventhPeriodTotal2OddEven]: "seventhPeriodTotal2OddEven",
  [MarketType.EightPeriodTotal2OddEven]: "eightPeriodTotal2OddEven",
  [MarketType.NinthPeriodTotal2OddEven]: "ninthPeriodTotal2OddEven",

  [MarketType.FirstPeriodBothTeamsToScore]: "firstPeriodBothTeamsToScore",
  [MarketType.SecondPeriodBothTeamsToScore]: "secondPeriodBothTeamsToScore",
  [MarketType.ThirdPeriodBothTeamsToScore]: "thirdPeriodBothTeamsToScore",
  [MarketType.FourthPeriodBothTeamsToScore]: "fourthPeriodBothTeamsToScore",
  [MarketType.FifthPeriodBothTeamsToScore]: "fifthPeriodBothTeamsToScore",
  [MarketType.SixthPeriodBothTeamsToScore]: "sixthPeriodBothTeamsToScore",
  [MarketType.SeventhPeriodBothTeamsToScore]: "seventhPeriodBothTeamsToScore",
  [MarketType.EightPeriodBothTeamsToScore]: "eightPeriodBothTeamsToScore",
  [MarketType.NinthPeriodBothTeamsToScore]: "ninthPeriodBothTeamsToScore",
};

const PLAYER_PROPS_BET_TYPES = [
  MarketType.Homeruns,
  MarketType.Strikeouts,
  MarketType.PassingYards,
  MarketType.PassingTouchdowns,
  MarketType.RushingYards,
  MarketType.ReceivingYards,
  MarketType.Touchdowns,
  MarketType.FieldGoalsMade,
  MarketType.PitcherHitsAllowed,
  MarketType.Points,
  MarketType.Shots,
  MarketType.Goals,
  MarketType.HitsRecorded,
  MarketType.Rebounds,
  MarketType.Assists,
  MarketType.DoubleDouble,
  MarketType.TripleDouble,
  MarketType.Receptions,
  MarketType.FirstTouchdown,
  MarketType.LastTouchdown,
  MarketType.ThreePointsMade,
];

const ONE_SIDER_PLAYER_PROPS_BET_TYPES = [
  MarketType.Touchdowns,
  MarketType.Goals,
  MarketType.FirstTouchdown,
  MarketType.LastTouchdown,
];
const SPECIAL_YES_NO_BET_TYPES = [MarketType.DoubleDouble, MarketType.TripleDouble];

const ODDS_TYPE = {
  American: "american-odds",
  Decimal: "decimal-odds",
  AMM: "normalized-implied-odds",
};

const POSITION_NAME = {
  Home: "home",
  Away: "away",
  Draw: "draw",
};

const POSITION_TYPE = {
  Home: 0,
  Away: 1,
  Draw: 2,
};

const FINAL_RESULT_TYPE = {
  Canceled: 0,
  Home: 1,
  Away: 2,
  Draw: 3,
};

const POSITION_NAME_TYPE_MAP = {
  [POSITION_NAME.Home]: POSITION_TYPE.Home,
  [POSITION_NAME.Away]: POSITION_TYPE.Away,
  [POSITION_NAME.Draw]: POSITION_TYPE.Draw,
};

const FINAL_RESULT_TYPE_POSITION_TYPE_MAP = {
  [FINAL_RESULT_TYPE.Home]: POSITION_TYPE.Home,
  [FINAL_RESULT_TYPE.Away]: POSITION_TYPE.Away,
  [FINAL_RESULT_TYPE.Draw]: POSITION_TYPE.Draw,
};

const MARKET_DURATION_IN_DAYS = 90;
const PARLAY_MAXIMUM_QUOTE = 0.01449275;

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

const STATUS = {
  Open: 0,
  Paused: 1,
  Resolved: 10,
  Canceled: 255,
};

const MAX_PERCENTAGE_DIFF_BETWEEN_ODDS = 10;
const MIN_ODDS_FOR_DIFF_CHECKING = 0.2;
const MINUTE_LIMIT_FOR_LIVE_TRADING_FOOTBALL = 85;

module.exports = {
  BET_TYPE: MarketType,
  MARKET_TYPE,
  PLAYER_PROPS_BET_TYPES,
  ONE_SIDER_PLAYER_PROPS_BET_TYPES,
  ODDS_TYPE,
  MARKET_DURATION_IN_DAYS,
  POSITION_NAME,
  POSITION_TYPE,
  POSITION_NAME_TYPE_MAP,
  PARLAY_MAXIMUM_QUOTE,
  FINAL_RESULT_TYPE_POSITION_TYPE_MAP,
  ZERO_ADDRESS,
  SPECIAL_YES_NO_BET_TYPES,
  STATUS,
  MAX_PERCENTAGE_DIFF_BETWEEN_ODDS,
  MIN_ODDS_FOR_DIFF_CHECKING,
  MINUTE_LIMIT_FOR_LIVE_TRADING_FOOTBALL,
};
