const Sport = {
  SOCCER: "Soccer",
  FOOTBALL: "Football",
  BASKETBALL: "Basketball",
  BASEBALL: "Baseball",
  HOCKEY: "Hockey",
  FIGHTING: "Fighting",
  TENNIS: "Tennis",
  ESPORTS: "eSports",
  CRICKET: "Cricket",
  MOTOSPORT: "Motosport",
  GOLF: "Golf",
  EMPTY: "",
};

const League = {
  NCAAF: 1,
  NFL: 2,
  MLB: 3,
  NBA: 4,
  NCAAB: 5,
  NHL: 6,
  UFC: 7,
  WNBA: 8,
  MLS: 10,
  EPL: 11,
  LIGUE_ONE: 12,
  BUNDESLIGA: 13,
  LA_LIGA: 14,
  SERIE_A: 15,
  UEFA_CL: 16,
  UEFA_EL: 17,
  FIFA_WC: 18,
  J1_LEAGUE: 19,
  IPL: 20,
  T20_BLAST: 21,
  IIHF_WORLD_CHAMPIONSHIP: 33,
  COPA_LIBERTADORES: 45,
  UEFA_EURO_QUALIFICATIONS: 50,
  EREDIVISIE: 57,
  PRIMEIRA_LIGA: 61,
  FIFA_WC_WOMEN: 76,
  ENGLAND_CUP: 132,
  FRANCE_CUP: 134,
  SPAIN_CUP: 138,
  ITALY_CUP: 141,
  TENNIS_GS: 153,
  TENNIS_MASTERS: 156,
  GERMANY_CUP: 209,
  BRAZIL_1: 268,
  UEFA_EURO_U21: 288,
  FIFA_WORLD_CUP_U20: 296,
  EUROLEAGUE: 399,
  FIBA_WORLD_CUP: 409,
  FORMULA1: 445,
  MOTOGP: 497,
  SAUDI_PROFESSIONAL_LEAGUE: 536,
  BOXING: 9196,
  UEFA_NATIONS_LEAGUE: 9806,
  CONCACAF_NATIONS_LEAGUE: 9821,
  CSGO: 9977,
  DOTA2: 9983,
  LOL: 10138,
  CONMEBOL_WC_QUALIFICATIONS: 10199,
  UEFA_CONFERENCE_LEAGUE: 10216,
  NON_TITLE_BOXING: 10595,
  GOLF_H2H: 100021,
  GOLF_WINNER: 100121,
};

const ScoringType = {
  POINTS: "points",
  GOALS: "goals",
  ROUNDS: "rounds",
  SETS: "sets",
  EMPTY: "",
};

const MatchResolveType = {
  OVERTIME: "overtime",
  REGULAR: "regular",
  EMPTY: "",
};

const PeriodType = {
  QUARTER: "quarter",
  HALF: "half",
  PERIOD: "period",
  ROUND: "round",
  INNING: "inning",
  SET: "set",
  EMPTY: "",
};

const Provider = {
  RUNDOWN: "rundown",
  ENETPULSE: "enetpulse",
  JSONODDS: "jsonOdds",
};

const LeagueMap = {
  [League.NCAAF]: {
    sport: Sport.FOOTBALL,
    id: League.NCAAF,
    label: "NCAA Football",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.QUARTER,
    isDrawAvailable: false,
    live: false,
  },
  [League.NFL]: {
    sport: Sport.FOOTBALL,
    id: League.NFL,
    label: "NFL",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.QUARTER,
    isDrawAvailable: false,
    live: false,
  },
  [League.MLB]: {
    sport: Sport.BASEBALL,
    id: League.MLB,
    label: "MLB",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.INNING,
    isDrawAvailable: false,
    live: true,
  },
  [League.NBA]: {
    sport: Sport.BASKETBALL,
    id: League.NBA,
    label: "NBA",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.QUARTER,
    isDrawAvailable: false,
    live: true,
  },
  [League.NCAAB]: {
    sport: Sport.BASKETBALL,
    id: League.NCAAB,
    label: "NCAA Basketball",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.QUARTER,
    isDrawAvailable: false,
    live: false,
  },
  [League.NHL]: {
    sport: Sport.HOCKEY,
    id: League.NHL,
    label: "NHL",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.PERIOD,
    isDrawAvailable: false,
    live: true,
  },
  [League.UFC]: {
    sport: Sport.FIGHTING,
    id: League.UFC,
    label: "UFC",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.ROUNDS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.ROUND,
    isDrawAvailable: false,
    live: false,
  },
  [League.WNBA]: {
    sport: Sport.BASKETBALL,
    id: League.WNBA,
    label: "WNBA",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.QUARTER,
    isDrawAvailable: false,
    live: false,
  },
  [League.MLS]: {
    sport: Sport.SOCCER,
    id: League.MLS,
    label: "MLS",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.EPL]: {
    sport: Sport.SOCCER,
    id: League.EPL,
    label: "EPL",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.LIGUE_ONE]: {
    sport: Sport.SOCCER,
    id: League.LIGUE_ONE,
    label: "Ligue 1",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },

  [League.BUNDESLIGA]: {
    sport: Sport.SOCCER,
    id: League.BUNDESLIGA,
    label: "Bundesliga",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.LA_LIGA]: {
    sport: Sport.SOCCER,
    id: League.LA_LIGA,
    label: "La Liga",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.SERIE_A]: {
    sport: Sport.SOCCER,
    id: League.SERIE_A,
    label: "Serie A",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.UEFA_CL]: {
    sport: Sport.SOCCER,
    id: League.UEFA_CL,
    label: "UEFA Champions League",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.UEFA_EL]: {
    sport: Sport.SOCCER,
    id: League.UEFA_EL,
    label: "UEFA Europa League",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.FIFA_WC]: {
    sport: Sport.SOCCER,
    id: League.FIFA_WC,
    label: "FIFA World Cup",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.J1_LEAGUE]: {
    sport: Sport.SOCCER,
    id: League.J1_LEAGUE,
    label: "J1 League",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.IPL]: {
    sport: Sport.CRICKET,
    id: League.IPL,
    label: "Indian Premier League",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.INNING,
    isDrawAvailable: false,
    live: false,
  },
  [League.T20_BLAST]: {
    sport: Sport.CRICKET,
    id: League.T20_BLAST,
    label: "T20 Blast",
    provider: Provider.RUNDOWN,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.INNING,
    isDrawAvailable: false,
    live: false,
  },
  [League.IIHF_WORLD_CHAMPIONSHIP]: {
    sport: Sport.HOCKEY,
    id: League.IIHF_WORLD_CHAMPIONSHIP,
    label: "IIHF World Championship",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.PERIOD,
    isDrawAvailable: true,
    live: false,
  },
  [League.COPA_LIBERTADORES]: {
    sport: Sport.SOCCER,
    id: League.COPA_LIBERTADORES,
    label: "Copa Libertadores",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.UEFA_EURO_QUALIFICATIONS]: {
    sport: Sport.SOCCER,
    id: League.UEFA_EURO_QUALIFICATIONS,
    label: "UEFA EURO 2024",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.EREDIVISIE]: {
    sport: Sport.SOCCER,
    id: League.EREDIVISIE,
    label: "Eredivisie",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.PRIMEIRA_LIGA]: {
    sport: Sport.SOCCER,
    id: League.PRIMEIRA_LIGA,
    label: "Primeira Liga",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.FIFA_WC_WOMEN]: {
    sport: Sport.SOCCER,
    id: League.FIFA_WC_WOMEN,
    label: "FIFA World Cup Women",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.ENGLAND_CUP]: {
    sport: Sport.SOCCER,
    id: League.ENGLAND_CUP,
    label: "FA Cup",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.FRANCE_CUP]: {
    sport: Sport.SOCCER,
    id: League.FRANCE_CUP,
    label: "Coupe de France",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.SPAIN_CUP]: {
    sport: Sport.SOCCER,
    id: League.SPAIN_CUP,
    label: "Copa del Rey",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.ITALY_CUP]: {
    sport: Sport.SOCCER,
    id: League.ITALY_CUP,
    label: "Coppa Italia",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.TENNIS_GS]: {
    sport: Sport.TENNIS,
    id: League.TENNIS_GS,
    label: "Grand Slam",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.SETS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.SET,
    isDrawAvailable: true,
    live: true,
  },
  [League.TENNIS_MASTERS]: {
    sport: Sport.TENNIS,
    id: League.TENNIS_MASTERS,
    label: "ATP Events",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.SETS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.SET,
    isDrawAvailable: true,
    live: true,
  },
  [League.GERMANY_CUP]: {
    sport: Sport.SOCCER,
    id: League.GERMANY_CUP,
    label: "DFB Pokal",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.BRAZIL_1]: {
    sport: Sport.SOCCER,
    id: League.BRAZIL_1,
    label: "Serie A",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.UEFA_EURO_U21]: {
    sport: Sport.SOCCER,
    id: League.UEFA_EURO_U21,
    label: "UEFA EURO U21",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
    tooltipKey: "common.football-tooltip",
  },
  [League.FIFA_WORLD_CUP_U20]: {
    sport: Sport.SOCCER,
    id: League.FIFA_WORLD_CUP_U20,
    label: "FIFA World Cup U20",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.EUROLEAGUE]: {
    sport: Sport.BASKETBALL,
    id: League.EUROLEAGUE,
    label: "Euroleague",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.QUARTER,
    isDrawAvailable: false,
    live: true,
  },
  [League.FIBA_WORLD_CUP]: {
    sport: Sport.SOCCER,
    id: League.FIBA_WORLD_CUP,
    label: "FIBA World Cup",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.POINTS,
    matchResolveType: MatchResolveType.OVERTIME,
    periodType: PeriodType.QUARTER,
    isDrawAvailable: false,
    live: false,
  },
  [League.FORMULA1]: {
    sport: Sport.MOTOSPORT,
    id: League.FORMULA1,
    label: "Formula 1",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.EMPTY,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.EMPTY,
    isDrawAvailable: false,
    live: false,
  },
  [League.MOTOGP]: {
    sport: Sport.MOTOSPORT,
    id: League.MOTOGP,
    label: "MotoGP",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.EMPTY,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.EMPTY,
    isDrawAvailable: false,
    live: false,
  },
  [League.SAUDI_PROFESSIONAL_LEAGUE]: {
    sport: Sport.SOCCER,
    id: League.SAUDI_PROFESSIONAL_LEAGUE,
    label: "Saudi Professional League",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: true,
  },
  [League.BOXING]: {
    sport: Sport.FIGHTING,
    id: League.BOXING,
    label: "Boxing",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.ROUNDS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.ROUND,
    isDrawAvailable: false,
    live: false,
  },
  [League.UEFA_NATIONS_LEAGUE]: {
    sport: Sport.SOCCER,
    id: League.UEFA_NATIONS_LEAGUE,
    label: "UEFA Nations League",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.CONCACAF_NATIONS_LEAGUE]: {
    sport: Sport.SOCCER,
    id: League.CONCACAF_NATIONS_LEAGUE,
    label: "CONCACAF Nations League",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.CSGO]: {
    sport: Sport.ESPORTS,
    id: League.CSGO,
    label: "CS GO",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.ROUNDS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.ROUND,
    isDrawAvailable: false,
    live: true,
  },
  [League.DOTA2]: {
    sport: Sport.ESPORTS,
    id: League.DOTA2,
    label: "DOTA 2",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.ROUNDS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.ROUND,
    isDrawAvailable: false,
    live: true,
  },
  [League.LOL]: {
    sport: Sport.ESPORTS,
    id: League.LOL,
    label: "LOL",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.ROUNDS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.ROUND,
    isDrawAvailable: false,
    live: true,
  },
  [League.CONMEBOL_WC_QUALIFICATIONS]: {
    sport: Sport.SOCCER,
    id: League.CONMEBOL_WC_QUALIFICATIONS,
    label: "CONMEBOL WC Qualification",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.UEFA_CONFERENCE_LEAGUE]: {
    sport: Sport.SOCCER,
    id: League.UEFA_CONFERENCE_LEAGUE,
    label: "UEFA Conference League",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.GOALS,
    matchResolveType: MatchResolveType.REGULAR,
    periodType: PeriodType.HALF,
    isDrawAvailable: true,
    live: false,
  },
  [League.NON_TITLE_BOXING]: {
    sport: Sport.FIGHTING,
    id: League.NON_TITLE_BOXING,
    label: "Boxing",
    provider: Provider.ENETPULSE,
    scoringType: ScoringType.ROUNDS,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.ROUND,
    isDrawAvailable: false,
    live: false,
  },
  [League.GOLF_H2H]: {
    sport: Sport.GOLF,
    id: League.GOLF_H2H,
    label: "Golf head-to-head",
    provider: Provider.JSONODDS,
    scoringType: ScoringType.EMPTY,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.EMPTY,
    isDrawAvailable: false,
    live: false,
  },
  [League.GOLF_WINNER]: {
    sport: Sport.GOLF,
    id: League.GOLF_WINNER,
    label: "Golf Tournament Winner",
    provider: Provider.JSONODDS,
    scoringType: ScoringType.EMPTY,
    matchResolveType: MatchResolveType.EMPTY,
    periodType: PeriodType.EMPTY,
    isDrawAvailable: false,
    live: false,
  },
};

module.exports = {
  Sport,
  League,
  ScoringType,
  MatchResolveType,
  PeriodType,
  Provider,
  LeagueMap,
};
