const bookmakersData = [
  {
    sportName: "Tennis Masters",
    sportId: "156",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "",
    tertiaryBookmaker: "",
  },
  {
    sportName: "Tennis Grand Slam",
    sportId: "153",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "",
    tertiaryBookmaker: "",
  },
  {
    sportName: "Tennis WTA",
    sportId: "152",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "",
    tertiaryBookmaker: "",
  },
  {
    sportName: "Brazil cup",
    sportId: "20002",
    primaryBookmaker: "bovada",
    secondaryBookmaker: "",
    tertiaryBookmaker: "",
  },
  {
    sportName: "MLS",
    sportId: "10",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "EPL",
    sportId: "11",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "FRA1",
    sportId: "12",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "GER1",
    sportId: "13",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "La Liga",
    sportId: "14",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "Seria A",
    sportId: "15",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "UEFA champions League",
    sportId: "16",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "",
    tertiaryBookmaker: "",
  },
  {
    sportName: "UEFA Europa League",
    sportId: "17",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "JPN1",
    sportId: "19",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "Copa Libertadores",
    sportId: "45",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "NET1",
    sportId: "57",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "POR1",
    sportId: "61",
    primaryBookmaker: "bovada",
    secondaryBookmaker: "pinnacle",
    tertiaryBookmaker: "",
  },
  { sportName: "Brazil", sportId: "268", primaryBookmaker: "bovada", secondaryBookmaker: "", tertiaryBookmaker: "" },
  {
    sportName: "Saudi League",
    sportId: "536",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "UEFA Conference League",
    sportId: "10216",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "UEFA Nations League",
    sportId: "9806",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "FIFA WC",
    sportId: "18",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "NFL",
    sportId: "2",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "MLB",
    sportId: "3",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "NHL",
    sportId: "6",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "NBA",
    sportId: "4",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "WNBA",
    sportId: "8",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
  {
    sportName: "Euroleague",
    sportId: "399",
    primaryBookmaker: "draftkings",
    secondaryBookmaker: "bovada",
    tertiaryBookmaker: "",
  },
];

module.exports = { bookmakersData };
