const leaguesData = [
  {
    name: "NCAAF",
    sportId: "1",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NCAAF",
    sportId: "1",
    typeId: "10001",
    marketName: "Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NCAAF",
    sportId: "1",
    typeId: "10002",
    marketName: "Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10001",
    marketName: "Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10002",
    marketName: "Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10031",
    marketName: "1st Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10032",
    marketName: "2nd Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10033",
    marketName: "3rd Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10034",
    marketName: "4th Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10041",
    marketName: "1st Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10042",
    marketName: "2nd Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10043",
    marketName: "3rd Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10044",
    marketName: "4th Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10071",
    marketName: "1st Half Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10072",
    marketName: "2nd Half Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10061",
    marketName: "1st Half Total Points Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NFL",
    sportId: "2",
    typeId: "10062",
    marketName: "2nd Half Total Pointss",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "MLB",
    sportId: "3",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "MLB",
    sportId: "3",
    typeId: "10001",
    marketName: "Run Line",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "MLB",
    sportId: "3",
    typeId: "10002",
    marketName: "Total Runs",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10001",
    marketName: "Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10002",
    marketName: "Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10031",
    marketName: "1st Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10032",
    marketName: "2nd Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10033",
    marketName: "3rd Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10034",
    marketName: "4th Quarter Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10041",
    marketName: "1st Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10042",
    marketName: "2nd Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10043",
    marketName: "3rd Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10044",
    marketName: "4th Quarter Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10071",
    marketName: "1st Half Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10072",
    marketName: "2nd Half Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10061",
    marketName: "1st Half Total Points Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NBA",
    sportId: "4",
    typeId: "10062",
    marketName: "2nd Half Total Pointss",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10001",
    marketName: "Puck Line",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10031",
    marketName: "1st Period Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10032",
    marketName: "2nd Period Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10033",
    marketName: "3rd Period Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10041",
    marketName: "1st Period Puck Line",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10042",
    marketName: "2nd Period Puck Line",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "NHL",
    sportId: "6",
    typeId: "10043",
    marketName: "3rd Period Puck Line",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "WNBA",
    sportId: "8",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "WNBA",
    sportId: "8",
    typeId: "10001",
    marketName: "Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "WNBA",
    sportId: "8",
    typeId: "10002",
    marketName: "Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "MLS",
    sportId: "10",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "MLS",
    sportId: "10",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "MLS",
    sportId: "10",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EPL",
    sportId: "11",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EPL",
    sportId: "11",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EPL",
    sportId: "11",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EPL",
    sportId: "11",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EPL",
    sportId: "11",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Ligue 1",
    sportId: "12",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Ligue 1",
    sportId: "12",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Ligue 1",
    sportId: "12",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Ligue 1",
    sportId: "12",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Ligue 1",
    sportId: "12",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Bundesliga",
    sportId: "13",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Bundesliga",
    sportId: "13",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Bundesliga",
    sportId: "13",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Bundesliga",
    sportId: "13",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Bundesliga",
    sportId: "13",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "La Liga",
    sportId: "14",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "La Liga",
    sportId: "14",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "La Liga",
    sportId: "14",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "La Liga",
    sportId: "14",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "La Liga",
    sportId: "14",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Serie A",
    sportId: "15",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Serie A",
    sportId: "15",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Serie A",
    sportId: "15",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Serie A",
    sportId: "15",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Serie A",
    sportId: "15",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Champions League",
    sportId: "16",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Champions League",
    sportId: "16",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Champions League",
    sportId: "16",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Champions League",
    sportId: "16",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Champions League",
    sportId: "16",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Europa League",
    sportId: "17",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Europa League",
    sportId: "17",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Europa League",
    sportId: "17",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Europa League",
    sportId: "17",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Europa League",
    sportId: "17",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "FIFA World Cup Qualifiers",
    sportId: "18",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "FIFA World Cup Qualifiers",
    sportId: "18",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "FIFA World Cup Qualifiers",
    sportId: "18",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "FIFA World Cup Qualifiers",
    sportId: "18",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "FIFA World Cup Qualifiers",
    sportId: "18",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "J1 League",
    sportId: "19",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "J1 League",
    sportId: "19",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "J1 League",
    sportId: "19",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa America",
    sportId: "44",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa America",
    sportId: "44",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa America",
    sportId: "44",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa Libertadores",
    sportId: "45",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa Libertadores",
    sportId: "45",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa Libertadores",
    sportId: "45",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa Libertadores",
    sportId: "45",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa Libertadores",
    sportId: "45",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA EURO 2024",
    sportId: "50",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA EURO 2024",
    sportId: "50",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA EURO 2024",
    sportId: "50",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Eredivisie",
    sportId: "57",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Eredivisie",
    sportId: "57",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Eredivisie",
    sportId: "57",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Primeira Liga",
    sportId: "61",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Primeira Liga",
    sportId: "61",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Primeira Liga",
    sportId: "61",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "WTA Events",
    sportId: "152",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "WTA Events",
    sportId: "152",
    typeId: "10001",
    marketName: "Game Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "WTA Events",
    sportId: "152",
    typeId: "10002",
    marketName: "Total Games",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Grand Slam",
    sportId: "153",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Grand Slam",
    sportId: "153",
    typeId: "10001",
    marketName: "Game Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Grand Slam",
    sportId: "153",
    typeId: "10002",
    marketName: "Total Games",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "ATP Events",
    sportId: "156",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "ATP Events",
    sportId: "156",
    typeId: "10001",
    marketName: "Game Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "ATP Events",
    sportId: "156",
    typeId: "10002",
    marketName: "Total Games",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Liga MX",
    sportId: "230",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Liga MX",
    sportId: "230",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Liga MX",
    sportId: "230",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Brazil - Serie A",
    sportId: "268",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Brazil - Serie A",
    sportId: "268",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Brazil - Serie A",
    sportId: "268",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Euroleague",
    sportId: "399",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Euroleague",
    sportId: "399",
    typeId: "10001",
    marketName: "Point Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Euroleague",
    sportId: "399",
    typeId: "10002",
    marketName: "Total Points",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Saudi Professional League",
    sportId: "536",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Saudi Professional League",
    sportId: "536",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Saudi Professional League",
    sportId: "536",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Nations League",
    sportId: "9806",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Nations League",
    sportId: "9806",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Nations League",
    sportId: "9806",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Nations League",
    sportId: "9806",
    typeId: "10017",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Nations League",
    sportId: "9806",
    typeId: "10018",
    marketName: "Team Total",
    type: "Total",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Conference League",
    sportId: "10216",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Conference League",
    sportId: "10216",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Conference League",
    sportId: "10216",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Super Cup",
    sportId: "20001",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Super Cup",
    sportId: "20001",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "UEFA Super Cup",
    sportId: "20001",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa do Brasil",
    sportId: "20002",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa do Brasil",
    sportId: "20002",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "Copa do Brasil",
    sportId: "20002",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EFL Championship",
    sportId: "20011",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EFL Championship",
    sportId: "20011",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "EFL Championship",
    sportId: "20011",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "England - EFL Cup",
    sportId: "20125",
    typeId: "0",
    marketName: "Moneyline",
    type: "Moneyline",
    enabled: "true",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "England - EFL Cup",
    sportId: "20125",
    typeId: "10001",
    marketName: "Goal Spread",
    type: "Spread",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
  {
    name: "England - EFL Cup",
    sportId: "20125",
    typeId: "10002",
    marketName: "Total Goals",
    type: "Total",
    enabled: "false",
    minOdds: "0.75",
    maxOdds: "0.25",
  },
];

module.exports = { leaguesData };
