const ONE_MINUTE = 60;

const TTL = {
  STAKERS: ONE_MINUTE * 30,
  LP: ONE_MINUTE * 30,
  MARKETS: ONE_MINUTE * 10,
  OPTION_TRANSACTIONS: ONE_MINUTE * 10,
  POSITION_BALANCE: ONE_MINUTE * 10,
  REFERRAL: ONE_MINUTE * 30,
  VAULT: ONE_MINUTE * 60,
};

module.export = TTL;
