const ONE_MINUTE = 60;
const ONE_HOUR = ONE_MINUTE * 60;
const ONE_DAY = ONE_HOUR * 24;

const TTL = {
  STAKERS: ONE_MINUTE * 30,
  LP: ONE_MINUTE * 30,
  LP_PNL: ONE_DAY,
  LP_TRANSACTIONS: ONE_MINUTE * 10,
  MARKETS: ONE_MINUTE * 10,
  OPTION_TRANSACTIONS: ONE_MINUTE * 10,
  POSITION_BALANCE: ONE_MINUTE * 10,
  REFERRAL: ONE_MINUTE * 30,
  VAULT_PNL: ONE_DAY,
  VAULT_TRANSACTIONS: ONE_MINUTE * 10,
  VAULT_USER_TRANSACTIONS: ONE_MINUTE * 10,
};

module.export = TTL;
