const streamEventOdds = {
  data: [
    {
      deep_link: null,
      fixture_id: "3DA34AEB6566",
      game_id: "41571-32765-2024-11-19",
      grouping_key: "default",
      id: "41571-32765-2024-11-19:draftkings:moneyline:draw",
      is_live: true,
      is_main: true,
      league: "UEFA - Nations League",
      limits: null,
      market: "Moneyline",
      name: "Draw",
      player_id: null,
      points: null,
      price: 4.8,
      selection: "Draw",
      selection_line: null,
      selection_points: null,
      sport: "soccer",
      sportsbook: "DraftKings",
      team_id: null,
      timestamp: 1732045800.7847786,
    },
    {
      deep_link: null,
      fixture_id: "3DA34AEB6566",
      game_id: "41571-32765-2024-11-19",
      grouping_key: "default",
      id: "41571-32765-2024-11-19:draftkings:moneyline:montenegro",
      is_live: true,
      is_main: true,
      league: "UEFA - Nations League",
      limits: null,
      market: "Moneyline",
      name: "Montenegro",
      player_id: null,
      points: null,
      price: 5.7,
      selection: "Montenegro",
      selection_line: null,
      selection_points: null,
      sport: "soccer",
      sportsbook: "DraftKings",
      team_id: null,
      timestamp: 1732045800.7847786,
    },
    {
      deep_link: null,
      fixture_id: "3DA34AEB6566",
      game_id: "41571-32765-2024-11-19",
      grouping_key: "default:2",
      id: "41571-32765-2024-11-19:draftkings:total_points:over_2",
      is_live: true,
      is_main: true,
      league: "UEFA - Nations League",
      limits: null,
      market: "Total Points",
      name: "Over 2",
      player_id: null,
      points: 2,
      price: 1.769,
      selection: "",
      selection_line: "over",
      selection_points: 2,
      sport: "soccer",
      sportsbook: "DraftKings",
      team_id: null,
      timestamp: 1732045800.7847786,
    },
  ],
  entry_id: "1730079534820-2",
  type: "odds",
};

const streamEventLockedOdds = {
  data: [
    {
      deep_link: null,
      fixture_id: "3DA34AEB6566",
      game_id: "41571-32765-2024-11-19",
      grouping_key: "default:2",
      id: "41571-32765-2024-11-19:draftkings:total_points:over_2",
      is_live: true,
      is_main: true,
      league: "UEFA - Nations League",
      limits: null,
      market: "Total Points",
      name: "Over 2",
      player_id: null,
      points: 2,
      price: 1.769,
      selection: "",
      selection_line: "over",
      selection_points: 2,
      sport: "soccer",
      sportsbook: "DraftKings",
      team_id: null,
      timestamp: 1732045800.7847786,
    },
  ],
  entry_id: "1730079534820-2",
  type: "locked-odds",
};

// simulates multiple events
const streamOddsEvents = [streamEventOdds, streamEventLockedOdds];
const streamOddsEventsData = [streamEventOdds.data, streamEventLockedOdds.data];

module.exports = { streamOddsEvents, streamOddsEventsData };
