const teams = [
  ["luton town", "luton"],
  ["ath.bilbao", "athletic bilbao"],
  ["atl.madrid", "atletico madrid"],
  ["fc porto", "porto"],
  ["psv eindhoven", "psv"],
  ["borussia dortmund", "dortmund"],
  ["internazionale", "inter"],
  ["fk qarabag", "qarabag"],
  ["stade rennais", "rennes"],
  ["ac milan", "milan"],
  ["as roma", "roma"],
  ["feyenoord rotterdam", "feyenoord"],
  ["sporting cp", "sporting"],
  ["olympique marseille", "marseille"],
  ["shakhtar donetsk", "shakhtar"],
  ["sparta prague", "sparta praha"],
  ["bodoe/glimt", "bodo"],
  ["ludogorets razgrad", "ludogorets"],
  ["slovan bratislava", "slovan b."],
  ["eintracht frankfurt", "eintracht"],
  ["union st.gilloise", "st.gilloise"],
  ["sturm graz", "sturm"],
  ["legia warszawa", "legia"],
  ["real betis", "real betis"],
  ["bayer leverkusen", "leverkusen"],
  ["olympique lyon", "lyon"],
  ["manchester united", "man.utd"],
  ["brighton & hove albion", "brighton"],
  ["nottingham forest", "nott.forest"],
  ["manchester city", "man.city"],
  ["arsenal fc", "arsenal"],
  ["newcastle united", "newcastle"],
  ["brentford fc", "brentford"],
  ["olympiakos", "olympiacos"],
  ["real sociedad", "real sociedad"],
  ["alavés", "alaves"],
  ["almería", "almeria"],
  ["villarreal", "villareal"],
  ["borussia monchengladbach", "m' gladbach"],
  ["vfl bochum", "bochum"],
  ["vfb stuttgart", "stuttgart"],
  ["fc cologne", "koln"],
  ["werder bremen", "werder"],
  ["sv darmstadt 98", "darmstadt"],
  ["bayern munich", "bayern"],
  ["1. fc heidenheim", "heidenheim"],
  ["fc union berlin", "union berlin"],
  ["fc utrecht", "utrecht"],
  ["fortuna sittard", "fortuna s."],
  ["pec zwolle", "zwolle"],
  ["sparta rotterdam", "sparta"],
  ["al-raed", "al raed"],
  ["al-taawoun", "al taawon"],
  ["al fateh fc", "al fateh"],
  ["damac fc", "dhamk"],
  ["al ahli jeddah", "al ahli"],
  ["al hazem", "al hazm"],
  ["inter miami cf", "inter miami"],
  ["real salt lake", "salt lake"],
  ["columbus crew", "columbus"],
  ["atlanta united fc", "atlanta united"],
  ["los angeles fc", "los angeles"],
  ["seattle sounders", "seattle"],
  ["liverpool fc", "liverpool"],
  ["burnley fc", "burnley"],
  ["everton fc", "everton"],
  ["fulham fc", "fulham"],
  ["afc bournemouth", "bournemouth"],
  ["inter milano", "inter"],
  ["ssc napoli", "napoli"],
  ["fc barcelona", "barcelona"],
  ["qarabag fk", "qarabag"],
  ["sc braga", "braga"],
  ["toulouse fc", "toulouse"],
  ["sl benfica", "benfica"],
  ["sc freiburg", "freiburg"],
  ["rc lens", "lens"],
  ["galatasaray istanbul", "galatasaray"],
  ["young boys bern", "young boys"],
  ["fc shakhtar donetsk", "shakhtar"],
  ["stade rennes", "rennes"],
  ["sporting lisbon", "sporting"],
  ["kaa gent", "gent"],
  ["maccabi haifa fc", "maccabi haifa"],
  ["pfc ludogorets 1945 razgrad", "ludogorets"],
  ["servette geneva", "servette"],
  ["ajax amsterdam", "ajax"],
  ["real betis seville", "betis"],
  ["sk slovan bratislava", "slovan b."],
  ["sk sturm graz", "sturm"],
  ["union saint-gilloise", "st.gilloise"],
  ["ferencvarosi budapest", "ferencvaros"],
  ["olympiacos piraeus", "olympiacos"],
  ["molde fk", "molde"],
  ["orlando magic", "orlando"],
  ["cleveland cavaliers", "cleveland"],
  ["detroit pistons", "detroit"],
  ["indiana pacers", "indiana"],
  ["brooklyn nets", "brooklyn"],
  ["toronto raptors", "toronto"],
  ["phoenix suns", "phoenix"],
  ["dallas mavericks", "dallas"],
  ["oklahoma city thunder", "oklahoma"],
  ["houston rockets", "houston"],
  ["new orleans pelicans", "new orleans"],
  ["boston celtics", "boston"],
  ["chicago bulls", "chicago"],
  ["charlotte hornets", "charlotte"],
  ["utah jazz", "utah"],
  ["los angeles lakers", "la lakers"],
  ["los angeles clippers", "la clippers"],
  ["la clippers", "la clippers"],
  ["golden state warriors", "golden state"],
  ["san antonio spurs", "san antonio"],
  ["sacramento kings", "sacramento"],
  ["inter milan", "inter"],
  ["hellas verona", "verona"],
  ["fc augsburg", "augsburg"],
  ["tsg hoffenheim", "hoffenheim"],
  ["paris saint-germain", "psg"],
  ["paris saint-germain fc", "psg"],
  ["lorient fc", "lorient"],
  ["fc lorient", "lorient"],
  ["lorient", "lorient"],
  ["le havre ac", "le havre"],
  ["as monaco", "monaco"],
  ["clermont foot", "clermont"],
  ["fc volendam", "volendam"],
  ["sc heerenveen", "heerenveen"],
  ["almere city fc", "almere"],
  ["go ahead eagles", "go ahead"],
  ["fc twente", "twente"],
  ["al ittihad j.", "al ittihad"],
  ["al-wehda", "al wahda"],
  ["al-ettifaq", "al ettifaq"],
  ["al shabab r.", "al shabab"],
  ["al nassr fc", "al nassr"],
  ["al nassr r.", "al nassr"],
  ["philadelphia 76ers", "philadelphia"],
  ["new york knicks", "new york"],
  ["washington wizards", "washington"],
  ["denver nuggets", "denver"],
  ["al fayha", "al fayha"],
  ["al tai", "al tai"],
  ["al-fayha", "al fayha"],
  ["al taee", "al tai"],
  ["al hilal saudi fc", "al hilal"],
  ["al fateh sc", "al fateh"],
  ["us lecce", "lecce"],
  ["udinese calcio", "udinese"],
  ["acf fiorentina", "fiorentina"],
  ["ac monza", "monza"],
  ["lecce", "lecce"],
  ["udinese", "udinese"],
  ["urawa red diamonds", "urawa"],
  ["kyoto sanga", "kyoto"],
  ["kyoto sanga fc", "kyoto"],
  ["gamba osaka", "gamba osaka"],
  ["tokyo verdy 1969", "tokyo verdy"],
  ["tokyo verdy", "tokyo verdy"],
  ["nagoya grampus", "nagoya"],
  ["fc tokyo", "tokyo"],
  ["sanfrecce hiroshima", "hiroshima"],
  ["kashima antlers", "kashima"],
  ["fc machida zelvia", "machida zelvia"],
  ["machida zelvia", "machida zelvia"],
  ["cerezo osaka", "cerezo osaka"],
  ["hokkaido consadole sapporo", "consadole sapporo"],
  ["consadole sapporo", "consadole sapporo"],
  ["júbilo iwata", "jubilo iwata"],
  ["jubilo iwata", "jubilo iwata"],
  ["kashiwa reysol", "kashiwa reysol"],
  ["shonan bellmare", "shonan bellmare"],
  ["sagan tosu", "sagan tosu"],
  ["kawasaki frontale", "kawasaki frontale"],
  ["vissel kobe", "vissel kobe"],
  ["avispa fukuoka", "avispa fukuoka"],
  ["albirex niigata", "albirex niigata"],
  ["yokohama f. marinos", "yokohama f. marinos"],
  ["osasuna", "osasuna"],
  ["mallorca", "mallorca"],
  ["ca osasuna", "osasuna"],
  ["real club deportivo mallorca", "mallorca"],
  ["villarreal cf", "villareal"],
  ["real madrid cf", "real madrid"],
  ["real madrid", "real madrid"],
  ["ud almería", "almeria"],
  ["cádiz cf", "cadiz"],
  ["cádiz", "cadiz"],
  ["ud las palmas", "las palmas"],
  ["las palmas", "las palmas"],
  ["athletic club bilbao", "athletic bilbao"],
  ["athletic bilbao", "athletic bilbao"],
  ["sevilla fc", "sevilla"],
  ["sevilla", "sevilla"],
  ["valencia cf", "valencia"],
  ["valencia", "valencia"],
  ["girona fc", "girona"],
  ["girona", "girona"],
  ["barcelona", "barcelona"],
  ["rayo vallecano", "rayo vallecano"],
  ["granada cf", "granada"],
  ["granada", "granada"],
  ["real club celta de vigo", "celta vigo"],
  ["celta vigo", "celta vigo"],
  ["real betis balompié", "real betis"],
  ["real sociedad de fútbol", "real sociedad"],
  ["club atlético de madrid", "atletico madrid"],
  ["atletico madrid", "atletico madrid"],
  ["deportivo alavés", "alaves"],
  ["getafe cf", "getafe"],
  ["getafe", "getafe"],
  ["olympique lyonnais", "lyon"],
  ["lyon", "lyon"],
  ["rc strasbourg alsace", "strasbourg"],
  ["strasbourg", "strasbourg"],
  ["lille osc", "lille"],
  ["lille", "lille"],
  ["ogc nice côte d'azur", "nice"],
  ["nice", "nice"],
  ["fc metz", "metz"],
  ["metz", "metz"],
  ["stade de reims", "reims"],
  ["stade rennais fc", "rennes"],
  ["racing club de lens", "lens"],
  ["lens", "lens"],
  ["montpellier hsc", "montpellier"],
  ["montpellier", "montpellier"],
  ["toulouse", "toulouse"],
  ["stade brestois 29", "brest"],
  ["brest", "brest"],
  ["clermont foot 63", "clermont"],
  ["as monaco fc", "monaco"],
  ["fc nantes", "nantes"],
  ["nantes", "nantes"],
  ["olympique de marseille", "marseille"],
  ["marseille", "marseille"],
  ["bologna fc 1909", "bologna"],
  ["bologna", "bologna"],
  ["juventus fc", "juventus"],
  ["juventus", "juventus"],
  ["us salernitana 1919", "salernitana"],
  ["salernitana", "salernitana"],
  ["hellas verona fc", "verona"],
  ["genoa cfc", "genoa"],
  ["genoa", "genoa"],
  ["fc internazionale milano", "inter"],
  ["ss lazio", "lazio"],
  ["lazio", "lazio"],
  ["monza", "monza"],
  ["frosinone calcio", "frosinone"],
  ["frosinone", "frosinone"],
  ["empoli fc", "empoli"],
  ["empoli", "empoli"],
  ["us sassuolo calcio", "sassuolo"],
  ["sassuolo", "sassuolo"],
  ["cagliari calcio", "cagliari"],
  ["cagliari", "cagliari"],
  ["torino fc", "torino"],
  ["torino", "torino"],
  ["fiorentina", "fiorentina"],
  ["napoli", "napoli"],
  ["bayer 04 leverkusen", "leverkusen"],
  ["sv werder bremen", "werder"],
  ["vfl bochum 1848", "bochum"],
  ["1. fc heidenheim 1846", "heidenheim"],
  ["1. fc köln", "koln"],
  ["vfb stuttgart 1893", "stuttgart"],
  ["borussia vfl mönchengladbach", "m' gladbach"],
  ["bv borussia 09 dortmund", "dortmund"],
  ["sv darmstadt 1898", "darmstadt"],
  ["vfl wolfsburg", "wolfsburg"],
  ["1. fsv mainz 05", "mainz"],
  ["mainz", "mainz"],
  ["rasenballsport leipzig", "leipzig"],
  ["rb leipzig", "leipzig"],
  ["1. fc union berlin", "union berlin"],
  ["tsg 1899 hoffenheim", "hoffenheim"],
  ["fc bayern münchen", "bayern"],
  ["chelsea fc", "chelsea"],
  ["chelsea", "chelsea"],
  ["bournemouth", "bournemouth"],
  ["sheffield united fc", "sheffield"],
  ["sheffield united", "sheffield"],
  ["tottenham hotspur fc", "tottenham"],
  ["tottenham hotspur", "tottenham"],
  ["burnley", "burnley"],
  ["nottingham forest fc", "nott.forest"],
  ["crystal palace fc", "crystal palace"],
  ["crystal palace", "crystal palace"],
  ["aston villa fc", "aston villa"],
  ["aston villa", "aston villa"],
  ["liverpool", "liverpool"],
  ["wolverhampton wanderers fc", "wolves"],
  ["wolverhampton", "wolves"],
  ["brighton & hove albion fc", "brighton"],
  ["manchester united fc", "man.utd"],
  ["newcastle united fc", "newcastle"],
  ["manchester city fc", "man.city"],
  ["west ham united fc", "west ham"],
  ["west ham united", "west ham"],
  ["luton town fc", "luton"],
  ["fulham", "fulham"],
  ["everton", "everton"],
  ["atlanta braves", "atlanta braves"],
  ["san diego padres", "san diego padres"],
  ["minnesota twins", "minnesota twins"],
  ["cleveland guardians", "cleveland guardians"],
  ["st. louis cardinals", "st. louis cardinals"],
  ["new york mets", "new york mets"],
  ["baltimore orioles", "baltimore orioles"],
  ["toronto blue jays", "toronto blue jays"],
  ["los angeles dodgers", "los angeles dodgers"],
  ["arizona diamondbacks", "arizona diamondbacks"],
  ["oakland athletics", "oakland athletics"],
  ["colorado rockies", "colorado rockies"],
  ["houston astros", "houston astros"],
  ["los angeles angels", "los angeles angels"],
  ["chicago cubs", "chicago cubs"],
  ["kansas city royals", "kansas city royals"],
  ["detroit tigers", "detroit tigers"],
  ["chicago white sox", "chicago white sox"],
  ["new york yankees", "new york yankees"],
  ["seattle mariners", "seattle mariners"],
  ["tampa bay rays", "tampa bay rays"],
  ["boston red sox", "boston red sox"],
  ["washington nationals", "washington nationals"],
  ["cincinnati reds", "cincinnati reds"],
  ["pittsburgh pirates", "pittsburgh pirates"],
  ["san francisco giants", "san francisco giants"],
  ["philadelphia phillies", "philadelphia phillies"],
  ["texas rangers", "texas rangers"],
  ["miami marlins", "miami marlins"],
  ["miami heat", "miami heat"],
  ["milwaukee bucks", "milwaukee bucks"],
  ["milwaukee brewers", "milwaukee brewers"],
  ["switzerland", "switzerland"],
  ["germany", "germany"],
  ["belgium", "belgium"],
  ["romania", "romania"],
  ["türkiye", "turkey"],
  ["turkey", "turkey"],
  ["turkiye", "turkey"],
  ["portugal", "portugal"],
  ["georgia", "georgia"],
  ["czechia", "czechia"],
  ["netherlands", "netherlands"],
  ["france", "france"],
  ["poland", "poland"],
  ["austria", "austria"],
  ["slovakia", "slovakia"],
  ["spain", "spain"],
  ["italy", "italy"],
  ["denmark", "denmark"],
  ["england", "england"],
  ["slovenia", "slovenia"],
  ["serbia", "serbia"],
  ["scotland", "scotland"],
  ["albania", "albania"],
  ["hungary", "hungary"],
  ["croatia", "croatia"],
  ["ukraine", "ukraine"],
  ["xtreme gaming", "xtreme gaming"],
  ["team falcons", "team falcons"],
  ["betboom team", "betboom team"],
  ["aurora", "aurora"],
  ["heroic", "heroic"],
  ["azure ray", "azure ray"],
  ["team heroic", "heroic"],
  ["olympiacos", "olympiacos"],
  ["olympiacos b.c.", "olympiacos"],
  ["panathinaikos", "panathinaikos"],
  ["fenerbahce", "fenerbahce"],
  ["panathinaikos opap", "panathinaikos"],
  ["fenerbahce beko", "fenerbahce"],
  ["deportivo alaves", "alaves"],
  ["inter", "inter"],
  ["tomas martin etcheverry", "tomas etcheverry"],
  ["tomas etcheverry", "tomas etcheverry"],
  ["arthur cazaux", "arthur cazaux"],
  ["taylor fritz", "taylor fritz"],
  ["federico coria", "federico coria"],
  ["alexei popyrin", "alexei popyrin"],
  ["thanasi kokkinakis", "thanasi kokkinakis"],
  ["flavio cobolli", "flavio cobolli"],
  ["hamad medjedovic", "hamad medjedovic"],
  ["jan-lennard struff", "jan-lennard struff"],
  ["roman andres burruchaga", "roman andres burruchaga"],
  ["roberto carballes baena", "roberto carballes baena"],
  ["constant lestienne", "constant lestienne"],
  ["gregoire barrere", "gregoire barrere"],
  ["alexander bublik", "alexander bublik"],
  ["daniel evans", "daniel evans"],
  ["holger rune", "holger rune"],
  ["novak djokovic", "novak djokovic"],
  ["pierre-hugues herbert", "pierre-hugues herbert"],
  ["corentin moutet", "corentin moutet"],
  ["alexander shevchenko", "alexander shevchenko"],
  ["henri squire", "henri squire"],
  ["felix auger-aliassime", "felix auger-aliassime"],
  ["matteo arnaldi", "matteo arnaldi"],
  ["alexandre muller", "alexandre muller"],
  ["karen khachanov", "karen khachanov"],
  ["jozef kovalik", "jozef kovalik"],
  ["sebastian baez", "sebastian baez"],
  ["sebastian ofner", "sebastian ofner"],
  ["pavel kotov", "pavel kotov"],
  ["stan wawrinka", "stan wawrinka"],
  ["francisco cerundolo", "francisco cerundolo"],
  ["filip misolic", "filip misolic"],
  ["denis shapovalov", "denis shapovalov"],
  ["frances tiafoe", "frances tiafoe"],
  ["fabio fognini", "fabio fognini"],
  ["tommy paul", "tommy paul"],
  ["gael monfils", "gael monfils"],
  ["lorenzo musetti", "lorenzo musetti"],
  ["daniil medvedev", "daniil medvedev"],
  ["miomir kecmanovic", "miomir kecmanovic"],
  ["lorenzo sonego", "lorenzo sonego"],
  ["zhizhen zhang", "zhizhen zhang"],
  ["andrey rublev", "andrey rublev"],
  ["pedro martinez", "pedro martinez"],
  ["hubert hurkacz", "hubert hurkacz"],
  ["brandon nakashima", "brandon nakashima"],
  ["carlos alcaraz", "carlos alcaraz"],
  ["jesper de jong", "jesper de jong"],
  ["fabian marozsan", "fabian marozsan"],
  ["grigor dimitrov", "grigor dimitrov"],
  ["zizou bergs", "zizou bergs"],
  ["maximilian marterer", "maximilian marterer"],
  ["richard gasquet", "richard gasquet"],
  ["jannik sinner", "jannik sinner"],
  ["daniel altmaier", "daniel altmaier"],
  ["stefanos tsitsipas", "stefanos tsitsipas"],
  ["sebastian korda", "sebastian korda"],
  ["soonwoo kwon", "soon-woo kwon"],
  ["soon-woo kwon", "soon-woo kwon"],
  ["coco gauff", "coco gauff"],
  ["iga swiatek", "iga swiatek"],
  ["donna vekic", "donna vekic"],
  ["anna kalinskaya", "anna kalinskaya"],
  ["cristina bucsa", "cristina bucsa"],
  ["jelena ostapenko", "jelena ostapenko"],
  ["camila osorio", "camila osorio"],
  ["danielle collins", "danielle collins"],
  ["ana bogdan", "ana bogdan"],
  ["viktorija golubic", "viktorija golubic"],
  ["yafan wang", "yafan wang"],
  ["sofia kenin", "sofia kenin"],
  ["xinyu wang", "xinyu wang"],
  ["varvara gracheva", "varvara gracheva"],
  ["rebecca sramkova", "rebecca sramkova"],
  ["irina-camelia begu", "irina-camelia begu"],
  ["jana fett", "jana fett"],
  ["liudmila samsonova", "liudmila samsonova"],
  ["katerina siniakova", "katerina siniakova"],
  ["katie volynets", "katie volynets"],
  ["hailey baptiste", "hailey baptiste"],
  ["elina svitolina", "elina svitolina"],
  ["irene burillo escorihuela", "irene burillo escorihuela"],
  ["yulia putintseva", "yulia putintseva"],
  ["zeynep sonmez", "zeynep sonmez"],
  ["sara errani", "sara errani"],
  ["katie boulter", "katie boulter"],
  ["arantxa rus", "arantxa rus"],
  ["yue yuan", "yue yuan"],
  ["lucija ciric bagaric", "lucija ciric bagaric"],
  ["mirra andreeva", "mirra andreeva"],
  ["victoria azarenka", "victoria azarenka"],
  ["madison keys", "madison keys"],
  ["magdalena frech", "magdalena frech"],
  ["erika andreeva", "erika andreeva"],
  ["lin zhu", "lin zhu"],
  ["ashlyn krueger", "ashlyn krueger"],
  ["elise mertens", "elise mertens"],
  ["petra martic", "petra martic"],
  ["anna blinkova", "anna blinkova"],
  ["tamara zidansek", "tamara zidansek"],
  ["naomi osaka", "naomi osaka"],
  ["marta kostyuk", "marta kostyuk"],
  ["bianca andreescu", "bianca andreescu"],
  ["elisabetta cocciaretto", "elisabetta cocciaretto"],
  ["clara tauson", "clara tauson"],
  ["ons jabeur", "ons jabeur"],
  ["olga danilovic", "olga danilovic"],
  ["anastasia pavlyuchenkova", "anastasia pavlyuchenkova"],
  ["anastasia potapova", "anastasia potapova"],
  ["dayana yastremska", "dayana yastremska"],
  ["caroline garcia", "caroline garcia"],
  ["viktoriya tomova", "viktoriya tomova"],
  ["bernarda pera", "bernarda pera"],
  ["linda noskova", "linda noskova"],
  ["marie bouzkova", "marie bouzkova"],
  ["amanda anisimova", "amanda anisimova"],
  ["chloe paquet", "chloe paquet"],
  ["marketa vondrousova", "marketa vondrousova"],
  ["jasmine paolini", "jasmine paolini"],
  ["diane parry", "diane parry"],
  ["moyuka uchijima", "moyuka uchijima"],
  ["sloane stephens", "sloane stephens"],
  ["emma navarro", "emma navarro"],
  ["anna karolina schmiedlova", "anna karolina schmiedlova"],
  ["paula badosa", "paula badosa"],
  ["angelique kerber", "angelique kerber"],
  ["mayar sherif", "mayar sherif"],
  ["peyton stearns", "peyton stearns"],
  ["emina bektas", "emina bektas"],
  ["nadia podoroska", "nadia podoroska"],
  ["renata zarazua", "renata zarazua"],
  ["daria kasatkina", "daria kasatkina"],
  ["aryna sabalenka", "aryna sabalenka"],
  ["elina avanesyan", "elina avanesyan"],
  ["tamara korpatsch", "tamara korpatsch"],
  ["maria lourdes carle", "maria lourdes carle"],
  ["kristina mladenovic", "kristina mladenovic"],
  ["sorana cirstea", "sorana cirstea"],
  ["zarina diyas", "zarina diyas"],
  ["mananchaya sawangkaew:", "mananchaya sawangkaew"],
  ["xinyu gao", "xinyu gao"],
  ["elena-gabriela ruse", "elena-gabriela ruse"],
  ["gabriela ruse", "elena-gabriela ruse"],
  ["sijia wei", "sijia wei"],
  ["xinxin yao", "xinxin yao"],
  ["arina rodionova", "arina rodionova"],
  ["anna bondar", "anna bondar"],
  ["jaqueline cristian", "jaqueline cristian"],
  ["han shi", "han shi"],
  ["meiling wang", "meiling wang"],
  ["ajla tomljanovic", "ajla tomljanovic"],
  ["yufei ren", "yufei ren"],
  ["yulia starodubtseva", "yulia starodubtseva"],
  ["shuai zhang", "shuai zhang"],
  ["giulio zeppieri", "giulio zeppieri"],
  ["tallon griekspoor", "tallon griekspoor"],
  ["luciano darderi", "luciano darderi"],
  ["alexander zverev", "alexander zverev"],
  ["david goffin", "david goffin"],
  ["alex de minaur", "alex de minaur"],
  ["jaume munar", "jaume munar"],
  ["mariano navone", "mariano navone"],
  ["tomas machac", "tomas machac"],
  ["dusan lajovic", "dusan lajovic"],
  ["casper ruud", "casper ruud"],
  ["alejandro davidovich fokina", "alejandro davidovich fokina"],
  ["arthur rinderknech", "arthur rinderknech"],
  ["grêmio fb porto alegrense", "gremio"],
  ["ec juventude", "juventude"],
  ["sc corinthians paulista", "corinthians"],
  ["fluminense fc", "fluminense"],
  ["cr flamengo", "flamengo"],
  ["cruzeiro ec", "cruzeiro"],
  ["cuiabá ec", "cuiaba"],
  ["clube atlético mineiro", "atletico mineiro"],
  ["criciuma ec", "criciuma"],
  ["club athletico paranaense", "athletico paranaense"],
  ["atlético goianiense", "atletico go"],
  ["fortaleza ec", "fortaleza"],
  ["ec bahia", "bahia"],
  ["ec vitória", "vitoria"],
  ["cr vasco da gama", "vasco da gama"],
  ["se palmeiras", "palmeiras"],
  ["sc internacional", "internacional"],
  ["botafogo fr", "botafogo"],
  ["são paulo fc", "sao paulo"],
  ["gremio", "gremio"],
  ["juventude", "juventude"],
  ["red bull bragantino", "bragantino"],
  ["corinthians", "corinthians"],
  ["fluminense", "fluminense"],
  ["flamengo", "flamengo"],
  ["cruzeiro", "cruzeiro"],
  ["cuiaba", "cuiaba"],
  ["atletico mg", "atletico mineiro"],
  ["criciuma", "criciuma"],
  ["athletico paranaense", "athletico paranaense"],
  ["atletico go", "atletico go"],
  ["fortaleza", "fortaleza"],
  ["bahia", "bahia"],
  ["vitoria", "vitoria"],
  ["vasco da gama", "vasco da gama"],
  ["palmeiras", "palmeiras"],
  ["internacional", "internacional"],
  ["botafogo rj", "botafogo"],
  ["sao paulo", "sao paulo"],
  ["edmonton oilers", "edmonton oilers"],
  ["florida panthers", "florida panthers"],
  ["argentina", "argentina"],
  ["peru", "peru"],
  ["canada", "canada"],
  ["chile", "chile"],
  ["ecuador", "ecuador"],
  ["venezuela", "venezuela"],
  ["mexico", "mexico"],
  ["jamaica", "jamaica"],
  ["usa", "usa"],
  ["united states", "usa"],
  ["uruguay", "uruguay"],
  ["bolivia", "bolivia"],
  ["panama", "panama"],
  ["costa rica", "costa rica"],
  ["paraguay", "paraguay"],
  ["brazil", "brazil"],
  ["colombia", "colombia"],
  ["ben shelton", "ben shelton"],
  ["ugo humbert", "ugo humbert"],
  ["alejandro tabilo", "alejandro tabilo"],
  ["nicolas jarry", "nicolas jarry"],
  ["adrian mannarino", "adrian mannarino"],
  ["jiri lehecka", "jiri lehecka"],
  ["jack draper", "jack draper"],
  ["arthur fils", "arthur fils"],
  ["jordan thompson", "jordan thompson"],
  ["cameron norrie", "cameron norrie"],
  ["roman safiullin", "roman safiullin"],
  ["marcos giron", "marcos giron"],
  ["nuno borges", "nuno borges"],
  ["laslo djere", "laslo djere"],
  ["alex michelsen", "alex michelsen"],
  ["giovanni mpetshi perricard", "giovanni mpetshi perricard"],
  ["mpetshi perricard", "mpetshi perricard"],
  ["matteo berrettini", "matteo berrettini"],
  ["christopher eubanks", "christopher eubanks"],
  ["dominik koepfer", "dominik koepfer"],
  ["pablo carreno busta", "pablo carreno busta"],
  ["yunchaokete bu", "yunchaokete bu"],
  ["facundo diaz acosta", "facundo acosta"],
  ["facundo acosta", "facundo acosta"],
  ["max purcell", "max purcell"],
  ["aleksandar vukic", "aleksandar vukic"],
  ["marton fucsovics", "marton fucsovics"],
  ["hugo gaston", "hugo gaston"],
  ["sumit nagal", "sumit nagal"],
  ["thiago seyboth wild", "thiago seyboth wild"],
  ["luca nardi", "luca nardi"],
  ["rinky hijikata", "rinky hijikata"],
  ["jakub mensik", "jakub mensik"],
  ["christopher o'connell", "christopher o'connell"],
  ["james duckworth", "james duckworth"],
  ["taro daniel", "taro daniel"],
  ["emil ruusuvuori", "emil ruusuvuori"],
  ["thiago monteiro", "thiago monteiro"],
  ["aleksandar kovacevic", "aleksandar kovacevic"],
  ["borna coric", "borna coric"],
  ["yoshihito nishioka", "yoshihito nishioka"],
  ["juncheng shang", "juncheng shang"],
  ["mackenzie mcdonald", "mackenzie mcdonald"],
  ["botic van de zandschulp", "botic van de zandschulp"],
  ["aslan karatsev", "aslan karatsev"],
  ["camilo ugo carabelli", "camilo ugo carabelli"],
  ["elena rybakina", "elena rybakina"],
  ["jessica pegula", "jessica pegula"],
  ["qinwen zheng", "qinwen zheng"],
  ["maria sakkari", "maria sakkari"],
  ["beatriz haddad maia", "beatriz haddad maia"],
  ["ekaterina alexandrova", "ekaterina alexandrova"],
  ["leylah fernandez", "leylah fernandez"],
  ["diana shnaider", "diana shnaider"],
  ["barbora krejcikova", "barbora krejcikova"],
  ["karolina muchova", "karolina muchova"],
  ["veronika kudermetova", "veronika kudermetova"],
  ["magda linette", "magda linette"],
  ["clara burel", "clara burel"],
  ["anhelina kalinina", "anhelina kalinina"],
  ["karolina pliskova", "karolina pliskova"],
  ["caroline dolehide", "caroline dolehide"],
  ["xiyu wang", "xiyu wang"],
  ["laura siegemund", "laura siegemund"],
  ["taylor townsend", "taylor townsend"],
  ["oceane dodin", "oceane dodin"],
  ["greet minnen", "greet minnen"],
  ["lucia bronzetti", "lucia bronzetti"],
  ["daria saville", "daria saville"],
  ["jessica bouzas maneiro", "jessica bouzas maneiro"],
  ["brenda fruhvirtova", "brenda fruhvirtova"],
  ["martina trevisan", "martina trevisan"],
  ["jule niemeier", "jule niemeier"],
  ["caroline wozniacki", "caroline wozniacki"],
  ["paula badosa ", "paula badosa"],
  ["nao hibino", "nao hibino"],
  ["zhuoxuan baz", "zhuoxuan baz"],
  ["harriet dart", "harriet dart"],
  ["sara sorribes tormo", "sara sorribes tormo"],
  ["lesia tsurenko", "lesia tsurenko"],
  ["deportivo toluca", "toluca"],
  ["club universidad nacional", "club universidad nacional"],
  ["querétaro fc", "queretaro fc"],
  ["mazatlán fc", "mazatlan fc"],
  ["club león", "leon"],
  ["atlético de san luis", "atletico de san luis"],
  ["cf pachuca", "pachuca"],
  ["club tigres de la universidad autónoma de nuevo león", "tigres"],
  ["cf cruz azul", "cruz azul"],
  ["cf monterrey", "monterrey"],
  ["club santos laguna", "santos laguna"],
  ["club puebla", "puebla"],
  ["fc juárez", "fc juarez"],
  ["club necaxa", "necaxa"],
  ["club de fútbol américa", "cf america"],
  ["cd guadalajara", "cd guadalajara"],
  ["atlas fc", "atlas"],
  ["club tijuana xoloitzcuintles de caliente", "tijuana"],
  ["puebla", "puebla"],
  ["santos laguna", "santos laguna"],
  ["tijuana", "tijuana"],
  ["queretaro fc", "queretaro fc"],
  ["atlas", "atlas"],
  ["fc juarez", "fc juarez"],
  ["cf america", "cf america"],
  ["necaxa", "necaxa"],
  ["tigres", "tigres"],
  ["toluca", "toluca"],
  ["mazatlan fc", "mazatlan fc"],
  ["leon", "leon"],
  ["monterrey", "monterrey"],
  ["pachuca", "pachuca"],
  ["atletico de san luis", "atletico de san luis"],
  ["cruz azul", "cruz azul"],
  ["united states u23", "usa"],
  ["usa u23", "usa"],
  ["anna-karolina schmiedlova", "anna karolina schmiedlova"],
  ["rfs", "rfs"],
  ["ue santa coloma", "ue santa coloma"],
  ["dinamo minsk", "dinamo minsk"],
  ["rapid wien", "rapid wien"],
  ["trabzonspor", "trabzonspor"],
  ["elfsborg", "elfsborg"],
  ["rijeka", "rijeka"],
  ["viktoria plzen", "viktoria plzen"],
  ["kryvbas", "kryvbas"],
  ["cercle brugge", "cercle brugge"],
  ["molde", "molde"],
  ["ajax", "ajax"],
  ["maccabi tel aviv", "maccabi tel aviv"],
  ["fk panevezys", "fk panevezys"],
  ["lugano", "lugano"],
  ["partizan beograd", "partizan beograd"],
  ["servette", "servette"],
  ["braga", "braga"],
  ["borac banja luka", "borac banja luka"],
  ["klaksvik", "klaksvik"],
  ["shamrock rovers", "shamrock rovers"],
  ["nk celje", "nk celje"],
  ["fk rīgas futbola skola", "rfs"],
  ["tic tapa ue santa coloma", "ue santa coloma"],
  ["fc dinamo minsk", "dinamo minsk"],
  ["lincoln red imps fc", "lincoln red imps fc"],
  ["sk rapid", "rapid wien"],
  ["trabzonspor kulübü", "trabzonspor"],
  ["if elfsborg", "elfsborg"],
  ["hnk rijeka", "rijeka"],
  ["fc viktoria plzeň", "viktoria plzen"],
  ["fk kryvbas kryvyi rih", "kryvbas"],
  ["cercle brugge ksv", "cercle brugge"],
  ["afc ajax", "ajax"],
  ["panathinaikos fc", "panathinaikos"],
  ["servette fc", "servette"],
  ["sporting braga", "braga"],
  ["maccabi tel aviv fc", "maccabi tel aviv"],
  ["fk panevėžys", "fk panevezys"],
  ["fc lugano", "lugano"],
  ["fk partizan beograd", "partizan beograd"],
  ["shamrock rovers fc", "shamrock rovers"],
  ["fk borac banja luka", "borac banja luka"],
  ["kí klaksvík", "klaksvik"],
  ["fc astana", "astana"],
  ["corvinul hunedoara", "corvinul hunedoara"],
  ["fehervar fc", "fehervar fc"],
  ["omonia nicosia", "omonia nicosia"],
  ["flora tallinn", "flora tallinn"],
  ["vikingur reykjavik", "vikingur reykjavik"],
  ["pyunik", "pyunik"],
  ["sabah fk", "sabah fk"],
  ["st. patrick's athletic", "st. patrick's athletic"],
  ["broendby if", "broendby if"],
  ["zira", "zira"],
  ["osijek", "osijek"],
  ["hapoel beer sheva", "hapoel beer sheva"],
  ["mlada boleslav", "mlada boleslav"],
  ["tromsoe", "tromsoe"],
  ["kilmarnock", "kilmarnock"],
  ["brann", "brann"],
  ["st. mirren", "st. mirren"],
  ["pafos fc", "pafos fc"],
  ["cska 1948", "cska 1948"],
  ["djurgaarden", "djurgaarden"],
  ["ilves", "ilves"],
  ["cfr cluj", "cfr cluj"],
  ["maccabi petach tikva", "maccabi petach tikva"],
  ["banik ostrava", "banik ostrava"],
  ["fc koebenhavn", "fc koebenhavn"],
  ["fc sheriff", "fc sheriff"],
  ["olimpija ljubljana", "olimpija ljubljana"],
  ["aek athens", "aek athens"],
  ["fc noah", "fc noah"],
  ["istanbul basaksehir", "istanbul basaksehir"],
  ["iberia 1999", "iberia 1999"],
  ["vojvodina", "vojvodina"],
  ["maribor", "maribor"],
  ["drita", "drita"],
  ["auda", "auda"],
  ["zrinjski mostar", "zrinjski mostar"],
  ["botev plovdiv", "botev plovdiv"],
  ["ordabasy shymkent", "ordabasy shymkent"],
  ["fk astana", "astana"],
  ["sc corvinul 1921 hunedoara", "corvinul hunedoara"],
  ["fehérvár fc", "fehervar fc"],
  ["ac omonia nicosia", "omonia nicosia"],
  ["st patrick's athletic fc", "st. patrick's athletic"],
  ["fc flora tallinn", "flora tallinn"],
  ["víkingur reykjavík", "vikingur reykjavik"],
  ["brøndby if", "broendby if"],
  ["kp legia warszawa", "legia warszawa"],
  ["pyunik fc", "pyunik"],
  ["fk ordabasy shymkent", "ordabasy shymkent"],
  ["zira ik", "zira"],
  ["nk osijek", "osijek"],
  ["djurgårdens if", "djurgaarden"],
  ["tampereen ilves", "ilves"],
  ["scs cfr 1907 cluj", "cfr cluj"],
  ["maccabi petah tikva fc", "maccabi petach tikva"],
  ["hapoel be'er sheva fc", "hapoel beer sheva"],
  ["fk mladá boleslav", "mlada boleslav"],
  ["tromsø il", "tromsoe"],
  ["kilmarnock fc", "kilmarnock"],
  ["sk brann", "brann"],
  ["saint mirren fc", "st. mirren"],
  ["fk sheriff tiraspol", "fc sheriff"],
  ["nk olimpija ljubljana", "olimpija ljubljana"],
  ["fk cska 1948 sofia", "cska 1948"],
  ["fc københavn", "fc koebenhavn"],
  ["fc baník ostrava", "banik ostrava"],
  ["aek athens fc", "aek athens"],
  ["fc iberia 1999", "fc iberia 1999"],
  ["medipol i̇stanbul başakşehir futbol kulübü", "istanbul basaksehir"],
  ["kf drita", "drita"],
  ["fk auda riga", "auda"],
  ["pfk botev plovdiv", "botev plovdiv"],
  ["hšk zrinjski mostar", "zrinjski mostar"],
  ["fk vojvodina novi sad", "vojvodina"],
  ["nk maribor", "maribor"],
  ["gent", "gent"],
  ["silkeborg", "silkeborg"],
  ["slask wroclaw", "slask wroclaw"],
  ["st. gallen", "st. gallen"],
  ["silkeborg if", "silkeborg"],
  ["wks śląsk wrocław", "slask wroclaw"],
  ["fc st.gallen 1879", "st. gallen"],
  ["dinamo zagreb", "dinamo zagreb"],
  ["fk crvena zvezda", "crvena zvezda"],
  ["young boys", "young boys"],
  ["slavia prague", "slavia prague"],
  ["galatasaray", "galatasaray"],
  ["fc midtjylland", "midtjylland"],
  ["malmoe ff", "malmoe"],
  ["dynamo kyiv", "dynamo kyiv"],
  ["salzburg", "salzburg"],
  ["gnk dinamo zagreb", "dinamo zagreb"],
  ["fk crvena zvezda beograd", "crvena zvezda"],
  ["fk bodø / glimt", "bodo"],
  ["bsc young boys", "young boys"],
  ["qarabağ ağdam fk", "qarabag"],
  ["sk slavia praha", "slavia prague"],
  ["galatasaray spor kulübü", "galatasaray"],
  ["šk slovan bratislava", "slovan b."],
  ["malmö ff", "malmoe"],
  ["ac sparta prague", "sparta praha"],
  ["fc dynamo kyiv", "dynamo kyiv"],
  ["fc salzburg", "salzburg"],
  ["ruzomberok", "ruzomberok"],
  ["vitoria de guimaraes", "vitoria de guimaraes"],
  ["paksi se", "paksi se"],
  ["tns", "tns"],
  ["haecken", "haecken"],
  ["puskas fc academy", "puskas academy fc"],
  ["wisla krakow", "wisla krakow"],
  ["hjk", "hjk"],
  ["mfk ružomberok", "ruzomberok"],
  ["vitória sc guimarães", "vitoria de guimaraes"],
  ["paksi fc", "paksi se"],
  ["the new saints fc", "tns"],
  ["bk häcken", "haecken"],
  ["puskás akadémia fc", "puskas academy fc"],
  ["wisła kraków", "wisla krakow"],
  ["helsingin jalkapalloklubi", "hjk"],
  ["lask", "lask"],
  ["fc fcsb", "fc fcsb"],
  ["APOEL Nicosia", "APOEL nicosia"],
  ["hearts", "hearts"],
  ["CS Petrocub", "CS Petrocub"],
  ["TSC Backa Topola", "TSC Backa Topola"],
  ["PAOK Thessaloniki FC", "PAOK Thessaloniki"],
  ["Besiktas", "Besiktas"],
  ["Anderlecht", "Anderlecht"],
  ["Jagiellonia Bialystok", "Jagiellonia Bialystok"],
  ["Linzer Athletik Sport Klub", "lask"],
  ["SC Fotbal Club FCSB SA", "fc fcsb"],
  ["APOEL FC", "APOEL nicosia"],
  ["Heart of Midlothian FC", "hearts"],
  ["CS Petrocub Hînceşti", "CS Petrocub"],
  ["FK TSC Bačka Topola", "TSC Backa Topola"],
  ["Beşiktaş Jimnastik Kulübü", "Besiktas"],
  ["RSC Anderlecht", "Anderlecht"],
  ["SSA Jagiellonia Białystok", "Jagiellonia Bialystok"],
];

const teamsMap = new Map(teams);

module.exports = { teamsMap };
