const KEYS = {
  MAINNET_ORDERS: "mainnetOrders",
  MAINNET_WATCHLIST: "mainnetWatchlistMap",
  DISPLAY_NAME: "displayNameMap",
  MAINNET_LEADERBOARD: "mainnetLeaderboard",
  MAINNET_COMPETITION: "mainnetCompetition",
  MAINNET_PROFILES: "mainnetProfiles",
  ROPSTEN_ORDERS: "ropstenOrders",
  ROPSTEN_WATCHLIST: "ropstenWatchlistMap",
  ROPSTEN_LEADERBOARD: "ropstenLeaderboard",
  ROPSTEN_COMPETITION: "ropstenCompetition",
  ROPSTEN_PROFILES: "ropstenProfiles",
  OPTIMISM_ORDERS: "optimismOrders",
  TOKEN: "tokenMap",
  VERIFIED_ACCOUNTS: "verifiedAccounts",
  TWITTER_ACCOUNTS: "twitterAccounts",
  TWITTER_IDS: "twitterIds",
  DISCORD_IDS: "discordIds",
  VERIFIED_ADDRESSES_DISCORD: "verifiedUsersDiscord",
  DISCORD_USERS: "discordUsers",
  ROYALE_USERS: "royaleUsers",
  ROYALE_USER_DATA: "royaleUserData",
  FAUCET_CONSUMERS: "faucetConsumers",
  GAME_FINISHERS: "gameFinishersMap",
  LEADERBOARD: {
    10: "optimismLeaderboard",
    137: "polygonLeaderboard",
    69: "kovanOpLeaderboard",
    80001: "mumbaiLeaderboard",
  },
  RANGED_AMM_LIQUIDITY: {
    10: "optimismRangedLiq",
    137: "polygonRangedLiq",
    69: "kovanOpRangedLiq",
    420: "goerliRangedLiq",
    80001: "mumbaiRangedLiq",
    56: "BSCRangedLiq",
    42161: "arbitrumRangedLiq",
  },
  OP_REWARDS: {
    10: "opRewards",
    69: "opKovanRewards",
  },
  OVERTIME_REWARDS: {
    10: "overtimeOpRewards",
    42: "overtimeOpKovanRewards",
  },
  TWAP_FOR_PERIOD: "twapMap",
  DISCOUNTS: {
    10: "optimismDiscounts",
    420: "opGoerliDiscounts",
    137: "polygonDiscounts",
    42161: "arbitrumDiscounts",
    56: "bscDiscounts",
  },
  OVERTIME_DISCOUNTS: {
    5: "goerliOvertimeDiscounts",
    10: "optimismOvertimeDiscounts",
    420: "opGoerliOvertimeDiscounts",
    137: "polygonOvertimeDiscounts",
    42161: "arbitrumOvertimeDiscounts",
  },
  ZEBRO_CAMPAIGN: { 10: "zebroCampaignOp", 420: "zebroCampaignOpGoerli" },
};

module.exports = KEYS;
