const KEYS = {
  TOKEN: "tokenMap",
  GAME_FINISHERS: "gameFinishersMap",
  USER_REFFERER_IDS: "userReffererIDsMap",
  THALES_IO_DAILY_STATS: "thalesIOStats",
  THALES_IO_WEEKLY_STATS: "thalesIOWeeklyStats",
  PARLAY_LEADERBOARD: {
    10: "overtimeOpParlayLeaderboard",
    420: "overtimeGoerliParlayLeaderboard",
    42161: "overtimeArbitrumParlayLeaderboard",
    8453: "overtimeBaseParlayLeaderboard",
  },
  THALES_MARKETS: {
    10: "thalesOpMarkets",
    137: "thalesPolygonMarkets",
    42161: "thalesArbMarkets",
    8453: "thalesBaseMarkets",
  },
  THALES_MARKETS_LAST_UPDATED_AT: {
    10: "thalesOpMarketsLastUpdate",
    137: "thalesPolygonMarketsLastUpdate",
    42161: "thalesArbMarketsLastUpdate",
    8453: "thalesBaseMarketsLastUpdate",
  },
  THALES_USDC_MARKETS: {
    10: "thalesUsdcOpMarkets",
    137: "thalesUsdcPolygonMarkets",
    42161: "thalesUsdcArbMarkets",
    8453: "thalesUsdcBaseMarkets",
  },
  THALES_USDC_MARKETS_LAST_UPDATED_AT: {
    10: "thalesUsdcOpMarketsLastUpdate",
    137: "thalesUsdcPolygonMarketsLastUpdate",
    42161: "thalesUsdcArbMarketsLastUpdate",
    8453: "thalesUsdcBaseMarketsLastUpdate",
  },
  OVERTIME_V2_OPEN_MARKETS: {
    10: "overtimeV2OpOpenMarkets",
    11155420: "overtimeV2OpSepoliaOpenMarkets",
    42161: "overtimeV2ArbOpenMarkets",
    8453: "overtimeV2BaseOpenMarkets",
  },
  OVERTIME_V2_NUMBER_OF_MARKETS: {
    10: "overtimeV2OpNumberOfMarkets",
    11155420: "overtimeV2OpSepoliaNumberOfMarkets",
    42161: "overtimeV2ArbNumberOfMarkets",
    8453: "overtimeV2BaseNumberOfMarkets",
  },
  OVERTIME_V2_CLOSED_MARKETS: {
    10: "overtimeV2OpClosedMarkets",
    11155420: "overtimeV2OpSepoliaClosedMarkets",
    42161: "overtimeV2ArbClosedMarkets",
    8453: "overtimeV2BaseClosedMarkets",
  },
  OVERTIME_V2_GAMES_INFO: "overtimeV2GamesInfo",
  OVERTIME_V2_PLAYERS_INFO: "overtimeV2PlayersInfo",
  OVERTIME_V2_PLAYERS_INFO_TESTNET: "overtimeV2PlayersInfoTestnet",
  OVERTIME_V2_LIVE_MARKETS: {
    10: "overtimeV2OpLiveMarkets",
    11155420: "overtimeV2OpSepoliaLiveMarkets",
    42161: "overtimeV2ArbLiveMarkets",
    8453: "overtimeV2BaseLiveMarkets",
  },
  OVERTIME_V2_LIVE_SCORES: "overtimeV2LiveScores",
  OVERTIME_V2_LIVE_TRADE_ADAPTER_MESSAGES: {
    10: "overtimeV2OpLiveTradeAdapterMessages",
    11155420: "overtimeV2SepoliaLiveTradeAdapterMessages",
    42161: "overtimeV2ArbLiveTradeAdapterMessages",
    8453: "overtimeV2BaseLiveTradeAdapterMessages",
  },
  OVERTIME_V2_LIVE_MARKETS_API_ERROR_MESSAGES: {
    10: "overtimeV2OpLiveMarketsApiErrorMessages",
    11155420: "overtimeV2SepoliaLiveMarketsApiErrorMessages",
    42161: "overtimeV2ArbLiveMarketsApiErrorMessages",
    8453: "overtimeV2BaseLiveMarketsApiErrorMessages",
  },

  OPTIC_ODDS_API_FIXTURES_BY_LEAGUE: "opticOddsApiFixturesByLeagueId",
  OPTIC_ODDS_API_ODDS_BY_LEAGUE: "opticOddsApiOddsByLeagueId",
  OPTIC_ODDS_API_RESULTS_BY_LEAGUE: "opticOddsApiResultsByLeagueId",
  OPTIC_ODDS_STREAM_EVENT_ODDS_ID_BY_GAME: "opticOddsStreamEventOddsIdByGameId",
  OPTIC_ODDS_STREAM_EVENT_RESULTS_BY_GAME: "opticOddsStreamEventResultsByGameId",
  TESTNET_OPTIC_ODDS_API_FIXTURES_BY_LEAGUE: "testnetOpticOddsApiFixturesByLeagueId",
  TESTNET_OPTIC_ODDS_API_ODDS_BY_LEAGUE: "testnetOpticOddsApiOddsByLeagueId",
  TESTNET_OPTIC_ODDS_API_RESULTS_BY_LEAGUE: "testnetOpticOddsApiResultsByLeagueId",
  TESTNET_OPTIC_ODDS_STREAM_EVENT_ODDS_ID_BY_GAME: "testnetOpticOddsStreamEventOddsIdByGameId",
  TESTNET_OPTIC_ODDS_STREAM_EVENT_RESULTS_BY_GAME: "testnetOpticOddsStreamEventResultsByGameId",

  RISK_MANAGEMENT_SPREAD_DATA: "riskManagementSpreadData",
  RISK_MANAGEMENT_SPREAD_DATA_TESTNET: "riskManagementSpreadDataTestnet",
  RISK_MANAGEMENT_BOOKMAKERS_DATA: "riskManagementBookmakersData",
  RISK_MANAGEMENT_BOOKMAKERS_DATA_TESTNET: "riskManagementBookmakersDataTestnet",
  RISK_MANAGEMENT_LEAGUES_DATA: "riskManagementLeaguesData",
  RISK_MANAGEMENT_LEAGUES_DATA_TESTNET: "riskManagementLeaguesDataTestnet",
  RISK_MANAGEMENT_TEAMS_MAP: "riskManagementTeamsMap",
  RISK_MANAGEMENT_TEAMS_MAP_TESTNET: "riskManagementTeamsMapTestnet",

  SOLANA_ADDRESSES: "solanaAddresses",
};

module.exports = KEYS;
