const ENDPOINTS = {
  ROOT: "/",
  TOKEN_PRICE: "/token/price",
  TOKEN_SUPLY: "/token/circulatingsupply",
  TOKEN_CAP: "/token/marketcap",
  ETH_BURNED: "/utils/ethburned",
  GAME_STARTED: "/game-started",
  GAME_ENDED: "/game-ended",
  GAME_FINISHERS: "/game-finishers",
  MEDIUM: "/medium",
  OP_REWARDS: "/rewards/:networkParam/:period",
  OP_REWARDS_V2: "/rewardsv2/:networkParam/:period",
  OVERTIME_REWARDS: "/overtime-rewards/:networkParam/:period",
  PARLAY_LEADERBOARD: "/parlay-leaderboard/:networkParam/:period",
  BANNERS: "/banners/:networkParam",
  BANNERS_IMAGE: "/banners/image/:imageName",
  PROMOTIONS: "/promotions",
  THALES_BANNERS: "/thales-banners/:networkParam",
  THALES_BANNERS_IMAGE: "/thales-banners/image/:imageName",
  LIVE_RESULT: "/live-result/:gameId",
  UPDATE_REFFERER_ID: "/update-refferer-id",
  GET_REFFERER_ID_ADDRESS: "/get-refferer-id-address/:reffererID",
  GET_ADDRESS_REFFERER_ID: "/get-address-refferer-id/:walletAddress",
  GET_REFFERER_MAP: "/get-refferer-map",
  ENETPULSE_RESULT: "/enetpulse-result/:sportId/:date",
  JSON_ODDS_DATA: "/json-odds-data/:sportParameter",

  MARCH_MADNESS: "/march-madness/:leaderboardType/:networkId",

  OVERTIME_SPORTS: "/overtime/networks/:networkParam/sports",
  OVERTIME_COLLATERALS: "/overtime/networks/:networkParam/collaterals",
  OVERTIME_MARKETS: "/overtime/networks/:networkParam/markets",
  OVERTIME_MARKET: "/overtime/networks/:networkParam/markets/:marketAddress",
  OVERTIME_USER_POSITIONS: "/overtime/networks/:networkParam/users/:userAddress/positions",
  OVERTIME_USER_TRANSACTIONS: "/overtime/networks/:networkParam/users/:userAddress/transactions",
  OVERTIME_MARKET_QUOTE: "/overtime/networks/:networkParam/markets/:marketAddress/quote",
  OVERTIME_PARLAY_QUOTE: "/overtime/networks/:networkParam/parlay/quote",

  THALES_COLLATERALS: "/thales/networks/:networkParam/collaterals",
  THALES_MARKETS: "/thales/networks/:networkParam/markets",
  THALES_MARKET: "/thales/networks/:networkParam/markets/:marketAddress",
  THALES_MARKET_BUY_QUOTE: "/thales/networks/:networkParam/markets/:marketAddress/buy-quote",
  THALES_MARKET_SELL_QUOTE: "/thales/networks/:networkParam/markets/:marketAddress/sell-quote",
  THALES_USER_POSITIONS: "/thales/networks/:networkParam/users/:userAddress/positions",
  THALES_USER_TRANSACTIONS: "/thales/networks/:networkParam/users/:userAddress/transactions",

  THALES_SPEED_MARKETS_BUY_PARAMS: "/thales/networks/:networkParam/speed-markets/buy",
  THALES_SPEED_MARKETS_USER_CLAIMABLE: "/thales/networks/:networkParam/users/:userAddress/speed-markets",
  THALES_SPEED_MARKETS_RESOLVE_PARAMS: "/thales/networks/:networkParam/speed-markets/resolve",
  THALES_SPEED_MARKETS_RESOLVE_OFFRAMP_PARAMS:
    "/thales/networks/:networkParam/speed-markets/:marketAddress/resolve-offramp",

  THALES_IO_VOLUME_DATA: "/thales/thales-io/volume-data",
  THALES_IO_USERS_DATA: "/thales/thales-io/users-data",
  THALES_IO_DAILY_STATS: "/thales/thales-io/stats",
  THALES_IO_WEEKLY_STATS: "/thales/thales-io/weekly-stats",
  THALES_IO_ECOSYSTEM_APPS: "/thales/thales-io/ecosystem-apps",
  THALES_IO_TIMELINE: "/thales/thales-io/timeline",
  OVERTIME_V2_MARKETS: "/overtime-v2/markets",
  OVERTIME_V2_MARKET: "/overtime-v2/markets/:marketAddress",
};

module.exports = ENDPOINTS;
