const ENDPOINTS = {
  ROOT: "/",
  TOKEN_PRICE: "/token/price",
  TOKEN_SUPLY: "/token/circulatingsupply",
  TOKEN_CAP: "/token/marketcap",
  GAME_STARTED: "/game-started",
  GAME_ENDED: "/game-ended",
  GAME_FINISHERS: "/game-finishers",
  MEDIUM: "/medium",
  OP_REWARDS: "/rewards/:networkParam/:period",
  OP_REWARDS_V2: "/rewardsv2/:networkParam/:period",
  OVERTIME_REWARDS: "/overtime-rewards/:networkParam/:period",
  PARLAY_LEADERBOARD: "/parlay-leaderboard/:networkParam/:period",
  BANNERS: "/banners/:networkParam",
  BANNERS_IMAGE: "/banners/image/:imageName",
  BANNERS_V2: "/banners-v2/:networkParam",
  BANNERS_V2_IMAGE: "/banners-v2/image/:imageName",
  PROMOTIONS: "/promotions",
  THALES_BANNERS: "/thales-banners/:networkParam",
  THALES_BANNERS_IMAGE: "/thales-banners/image/:imageName",
  SPEED_BANNERS: "/speed-banners/:networkParam",
  SPEED_BANNERS_IMAGE: "/speed-banners/image/:imageName",
  LIVE_RESULT: "/live-result/:gameId",
  UPDATE_REFFERER_ID: "/update-refferer-id",
  GET_REFFERER_ID_ADDRESS: "/get-refferer-id-address/:reffererID",
  GET_ADDRESS_REFFERER_ID: "/get-address-refferer-id/:walletAddress",
  GET_REFFERER_MAP: "/get-refferer-map",
  ENETPULSE_RESULT: "/enetpulse-result/:sportId/:date",
  JSON_ODDS_DATA: "/json-odds-data/:sportParameter",

  OVERTIME_SPORTS: "/overtime/networks/:networkParam/sports",
  OVERTIME_COLLATERALS: "/overtime/networks/:networkParam/collaterals",
  OVERTIME_MARKETS: "/overtime/networks/:networkParam/markets",
  OVERTIME_MARKET: "/overtime/networks/:networkParam/markets/:marketAddress",
  OVERTIME_USER_POSITIONS: "/overtime/networks/:networkParam/users/:userAddress/positions",
  OVERTIME_USER_TRANSACTIONS: "/overtime/networks/:networkParam/users/:userAddress/transactions",
  OVERTIME_MARKET_QUOTE: "/overtime/networks/:networkParam/markets/:marketAddress/quote",
  OVERTIME_PARLAY_QUOTE: "/overtime/networks/:networkParam/parlay/quote",

  THALES_COLLATERALS: "/thales/networks/:networkParam/collaterals",
  THALES_MARKETS: "/thales/networks/:networkParam/markets",
  THALES_MARKET: "/thales/networks/:networkParam/markets/:marketAddress",
  THALES_MARKETS_COUNT: "/thales/networks/:networkParam/market-count",
  THALES_MARKET_BUY_QUOTE: "/thales/networks/:networkParam/markets/:marketAddress/buy-quote",
  THALES_MARKET_SELL_QUOTE: "/thales/networks/:networkParam/markets/:marketAddress/sell-quote",
  THALES_USER_POSITIONS: "/thales/networks/:networkParam/users/:userAddress/positions",
  THALES_USER_TRANSACTIONS: "/thales/networks/:networkParam/users/:userAddress/transactions",

  THALES_SPEED_MARKETS_BUY_PARAMS: "/speed-markets/networks/:networkParam/buy",
  THALES_SPEED_MARKETS_USER_CLAIMABLE: "/speed-markets/networks/:networkParam/users/:userAddress/claimable",
  THALES_SPEED_MARKETS_RESOLVE_PARAMS: "/speed-markets/networks/:networkParam/resolve",
  THALES_SPEED_MARKETS_RESOLVE_OFFRAMP_PARAMS:
    "/speed-markets/networks/:networkParam/markets/:marketAddress/resolve-offramp",
  THALES_SPEED_MARKETS_SOLANA_ADDRESS: "/speed-markets/solana-address",
  THALES_SPEED_MARKETS_SOLANA_ADDRESS_FOR_ADDRESS: "/speed-markets/solana-address/:walletAddress",

  THALES_IO_VOLUME_DATA: "/thales/thales-io/volume-data",
  THALES_IO_USERS_DATA: "/thales/thales-io/users-data",
  THALES_IO_DAILY_STATS: "/thales/thales-io/stats",
  THALES_IO_WEEKLY_STATS: "/thales/thales-io/weekly-stats",
  THALES_IO_ECOSYSTEM_APPS: "/thales/thales-io/ecosystem-apps",
  THALES_IO_TIMELINE: "/thales/thales-io/timeline",

  OVERTIME_V2_SPORTS: "/overtime-v2/sports",
  OVERTIME_V2_MARKET_TYPES: "/overtime-v2/market-types",
  OVERTIME_V2_COLLATERALS: "/overtime-v2/networks/:networkParam/collaterals",
  OVERTIME_V2_MARKETS: "/overtime-v2/networks/:networkParam/markets",
  OVERTIME_V2_LIVE_MARKETS: "/overtime-v2/networks/:networkParam/live-markets",
  OVERTIME_V2_MARKET: "/overtime-v2/networks/:networkParam/markets/:marketAddress",
  OVERTIME_V2_GAMES_INFO: "/overtime-v2/games-info",
  OVERTIME_V2_PLAYERS_INFO: "/overtime-v2/players-info",
  OVERTIME_V2_LIVE_SCORES: "/overtime-v2/live-scores",
  OVERTIME_V2_GAME_INFO: "/overtime-v2/games-info/:gameId",
  OVERTIME_V2_PLAYER_INFO: "/overtime-v2/players-info/:playerId",
  OVERTIME_V2_LIVE_SCORE: "/overtime-v2/live-scores/:gameId",
  OVERTIME_V2_UPDATE_MERKLE_TREE: "/overtime-v2/update-merkle-tree",
  OVERTIME_V2_USER_HISTORY: "/overtime-v2/networks/:networkParam/users/:userAddress/history",
  OVERTIME_V2_QUOTE: "/overtime-v2/networks/:networkParam/quote",
  OVERTIME_V2_LIVE_TRADING_ADAPTER_MESSAGE_WRITE: "/overtime-v2/live-trading/write-message",
  OVERTIME_V2_LIVE_TRADING_ADAPTER_MESSAGE_READ:
    "/overtime-v2/live-trading/networks/:networkParam/read-message/request/:requestId",
  OVERTIME_V2_LIVE_TRADING_API_ERROR_MESSAGES_READ: "/overtime-v2/live-trading/networks/:networkParam/error-messages",
};

module.exports = ENDPOINTS;
