const ENDPOINTS = {
  ROOT: "/",
  AUTH: "/auth/:walletAddress",
  DISPLAY_NAME: "/display-name",
  DISPLAY_NAME_ADDRESS: "/display-name/:walletAddress",
  OPTIONS: "/options/:networkParam/:addressParam",
  ORDERS: "/orders/:networkParam",
  WATCHLIST: "/watchlist",
  WATCHLIST_ADDRESS: "/watchlist/:networkParam/:walletAddressParam",
  LEADERBOARD: "/leaderboard/:networkParam",
  RANGED_LIQUIDITY: "/ranged-liquidity/:networkParam",
  COMPETITION: "/competition/:networkParam",
  PROFILES: "/profiles/:networkParam",
  TOKEN_PRICE: "/token/price",
  TOKEN_SUPLY: "/token/circulatingsupply",
  TOKEN_CAP: "/token/marketcap",
  TWITTER: "/twitter",
  TWITTER_ADDRESS: "/twitter/:walletAddress",
  VERIFIED_USERS: "/verified-users",
  ETH_BURNED: "/utils/ethburned",
  THALES_ROYALE: "/thales-royale",
  ROYALE_USERS: "/royale-users",
  ROYALE_USER: "/royale-user/:walletAddress",
  ROYALE_USER_DATA: "/royale-user-data",
  GAME_STARTED: "/game-started",
  GAME_ENDED: "/game-ended",
  GAME_FINISHERS: "/game-finishers",
  MEDIUM: "/medium",
  OP_REWARDS: "/rewards/:networkParam/:period",
  OVERTIME_REWARDS: "/overtime-rewards/:networkParam/:period",
  PARLAY_LEADERBOARD: "/parlay-leaderboard/:networkParam/:period",
  DISCOUNTS: "/discounts/:networkParam",
  OVERTIME_DISCOUNTS: "/overtimeDiscounts/:networkParam",
  BANNER_IMAGE: "/banner-image/:imageIndex",
  BANNER_IMAGE_COUNT: "/banner-image-count",
  BANNER_JSON: "/banner-json/:jsonIndex",
  FIFA_REWARDS: "/fifa-rewards/:networkParam",
};

module.exports = ENDPOINTS;
